-- SAP Schema Expansion (Total 30+ Tables)
-- Generated by Antigravity

BEGIN;

-- ==========================================
-- 1. Configuration & Master Data (Global)
-- ==========================================

-- T001: Company Codes
CREATE TABLE IF NOT EXISTS T001 (
    BUKRS VARCHAR(4) PRIMARY KEY, -- Company Code
    BUTXT VARCHAR(25),            -- Name
    ORT01 VARCHAR(25),            -- City
    LAND1 VARCHAR(3)              -- Country
);
INSERT INTO T001 (BUKRS, BUTXT, ORT01, LAND1) VALUES
('1000', 'TranAI Global HQ', 'Berlin', 'DE'),
('2000', 'TranAI Americas', 'New York', 'US'),
('3000', 'TranAI Asia', 'Tokyo', 'JP'),
('4000', 'TranAI India', 'Bangalore', 'IN')
ON CONFLICT (BUKRS) DO NOTHING;

-- T001W: Plants/Branches
CREATE TABLE IF NOT EXISTS T001W (
    WERKS VARCHAR(4) PRIMARY KEY,
    NAME1 VARCHAR(30),
    STRAS VARCHAR(30),
    ORT01 VARCHAR(25)
);
INSERT INTO T001W (WERKS, NAME1, STRAS, ORT01) VALUES
('1000', 'Berlin Plant', 'Main St 1', 'Berlin'),
('1100', 'Hamburg Warehouse', 'Port Rd 5', 'Hamburg'),
('2000', 'NY Distribution', '5th Ave', 'New York'),
('3000', 'Tokyo Mfg', 'Shibuya 1', 'Tokyo')
ON CONFLICT (WERKS) DO NOTHING;

-- T002: Language Keys
CREATE TABLE IF NOT EXISTS T002 (
    SPRAS VARCHAR(2) PRIMARY KEY,
    SPTXT VARCHAR(20)
);
INSERT INTO T002 (SPRAS, SPTXT) VALUES
('EN', 'English'),
('DE', 'German'),
('FR', 'French'),
('JP', 'Japanese')
ON CONFLICT (SPRAS) DO NOTHING;

-- TCURC: Currency Codes
CREATE TABLE IF NOT EXISTS TCURC (
    WAERS VARCHAR(5) PRIMARY KEY,
    LTEXT VARCHAR(40)
);
INSERT INTO TCURC (WAERS, LTEXT) VALUES
('EUR', 'Euro'),
('USD', 'US Dollar'),
('JPY', 'Japanese Yen'),
('INR', 'Indian Rupee')
ON CONFLICT (WAERS) DO NOTHING;

-- KNA1: Customer Master (General)
CREATE TABLE IF NOT EXISTS KNA1 (
    KUNNR VARCHAR(10) PRIMARY KEY,
    NAME1 VARCHAR(35),
    ORT01 VARCHAR(35),
    LAND1 VARCHAR(3)
);
INSERT INTO KNA1 (KUNNR, NAME1, ORT01, LAND1) VALUES
('C001', 'Tech Corp', 'San Francisco', 'US'),
('C002', 'Auto Motto', 'Stuttgart', 'DE'),
('C003', 'Fast Retail', 'London', 'UK'),
('C004', 'Green Energy', 'Oslo', 'NO')
ON CONFLICT (KUNNR) DO NOTHING;

-- KNB1: Customer Master (Company Code)
CREATE TABLE IF NOT EXISTS KNB1 (
    KUNNR VARCHAR(10),
    BUKRS VARCHAR(4),
    AKONT VARCHAR(10),
    PRIMARY KEY (KUNNR, BUKRS)
);
INSERT INTO KNB1 (KUNNR, BUKRS, AKONT) VALUES
('C001', '2000', '140000'),
('C002', '1000', '140000'),
('C003', '1000', '140000')
ON CONFLICT (KUNNR, BUKRS) DO NOTHING;

-- ==========================================
-- 2. Sales & Distribution (SD)
-- ==========================================

-- VBAK: Sales Document: Header Data
CREATE TABLE IF NOT EXISTS VBAK (
    VBELN VARCHAR(10) PRIMARY KEY, -- Sales Doc
    ERDAT DATE,                    -- Created On
    ERNAM VARCHAR(12),             -- Created By
    KUNNR VARCHAR(10),             -- Sold-to
    NETWR DECIMAL(15,2),           -- Net Value
    WAERS VARCHAR(5)               -- Currency
);
INSERT INTO VBAK (VBELN, ERDAT, ERNAM, KUNNR, NETWR, WAERS) VALUES
('SO00001', '2023-11-01', 'USER1', 'C001', 5000.00, 'USD'),
('SO00002', '2023-11-05', 'USER2', 'C002', 12000.00, 'EUR'),
('SO00003', '2023-11-10', 'USER1', 'C001', 3500.00, 'USD')
ON CONFLICT (VBELN) DO NOTHING;

-- VBAP: Sales Document: Item Data
CREATE TABLE IF NOT EXISTS VBAP (
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    KWMENG DECIMAL(15,3), -- Order Quantity
    NETWR DECIMAL(15,2),  -- Net Value
    PRIMARY KEY (VBELN, POSNR)
);
INSERT INTO VBAP (VBELN, POSNR, MATNR, KWMENG, NETWR) VALUES
('SO00001', '10', 'MAT-MARLIN', 100, 4000.00),
('SO00001', '20', 'MAT-CHIP', 50, 1000.00),
('SO00002', '10', 'MAT-STEEL', 200, 12000.00)
ON CONFLICT (VBELN, POSNR) DO NOTHING;

-- LIKP: Delivery Header
CREATE TABLE IF NOT EXISTS LIKP (
    VBELN VARCHAR(10) PRIMARY KEY,
    ERDAT DATE,
    LIFEX VARCHAR(35) -- External ID
);
INSERT INTO LIKP (VBELN, ERDAT, LIFEX) VALUES
('DL00001', '2023-11-03', 'EXT-123'),
('DL00002', '2023-11-08', 'EXT-456')
ON CONFLICT (VBELN) DO NOTHING;

-- LIPS: Delivery Item
CREATE TABLE IF NOT EXISTS LIPS (
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    LFIMG DECIMAL(13,3), -- Delivered Qty
    PRIMARY KEY (VBELN, POSNR)
);
INSERT INTO LIPS (VBELN, POSNR, MATNR, LFIMG) VALUES
('DL00001', '10', 'MAT-MARLIN', 100),
('DL00002', '10', 'MAT-STEEL', 200)
ON CONFLICT (VBELN, POSNR) DO NOTHING;

-- VBRK: Billing Header
CREATE TABLE IF NOT EXISTS VBRK (
    VBELN VARCHAR(10) PRIMARY KEY,
    FKDAT DATE,           -- Billing Date
    NETWR DECIMAL(15,2),  -- Net Value
    KUNAG VARCHAR(10)     -- Payer
);
INSERT INTO VBRK (VBELN, FKDAT, NETWR, KUNAG) VALUES
('BILL001', '2023-11-04', 5000.00, 'C001'),
('BILL002', '2023-11-09', 12000.00, 'C002')
ON CONFLICT (VBELN) DO NOTHING;

-- VBRP: Billing Item
CREATE TABLE IF NOT EXISTS VBRP (
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    AUBEL VARCHAR(10), -- Sales Order Ref
    AUPOS VARCHAR(6),  -- Sales Item Ref
    NETWR DECIMAL(15,2),
    PRIMARY KEY (VBELN, POSNR)
);
INSERT INTO VBRP (VBELN, POSNR, AUBEL, AUPOS, NETWR) VALUES
('BILL001', '10', 'SO00001', '10', 4000.00),
('BILL001', '20', 'SO00001', '20', 1000.00),
('BILL002', '10', 'SO00002', '10', 12000.00)
ON CONFLICT (VBELN, POSNR) DO NOTHING;

-- ==========================================
-- 3. Controlling & Projects
-- ==========================================

-- CSKS: Cost Center Master
CREATE TABLE IF NOT EXISTS CSKS (
    KOSTL VARCHAR(10) PRIMARY KEY, -- Cost Center
    DATBI DATE,                    -- Valid To
    KOKRS VARCHAR(4),              -- Controlling Area
    BUKRS VARCHAR(4)
);
INSERT INTO CSKS (KOSTL, DATBI, KOKRS, BUKRS) VALUES
('CC100', '9999-12-31', '1000', '1000'),
('CC200', '9999-12-31', '1000', '1000'),
('CC300', '9999-12-31', '2000', '2000')
ON CONFLICT (KOSTL) DO NOTHING;

-- CSKT: Cost Center Text
CREATE TABLE IF NOT EXISTS CSKT (
    KOSTL VARCHAR(10),
    SPRAS VARCHAR(2),
    LTEXT VARCHAR(40),
    PRIMARY KEY (KOSTL, SPRAS)
);
INSERT INTO CSKT (KOSTL, SPRAS, LTEXT) VALUES
('CC100', 'EN', 'IT Department'),
('CC200', 'EN', 'HR Department'),
('CC300', 'EN', 'Sales Department')
ON CONFLICT (KOSTL, SPRAS) DO NOTHING;

-- PRPS: WBS Elements
CREATE TABLE IF NOT EXISTS PRPS (
    PSPNR VARCHAR(8) PRIMARY KEY, -- WBS Element (simplified)
    POST1 VARCHAR(40),            -- Description
    PSTART DATE,
    PENDE DATE
);
INSERT INTO PRPS (PSPNR, POST1, PSTART, PENDE) VALUES
('WBS-01', 'New Office Build', '2023-01-01', '2023-12-31'),
('WBS-02', 'SAP Implementation', '2023-06-01', '2024-06-01')
ON CONFLICT (PSPNR) DO NOTHING;

COMMIT;
