-- SAP High Volume Synthetic Data Generation
-- Generated by Antigravity
-- Uses generate_series to create bulk data

BEGIN;

-- 1. Generate 100 New Vendors (V100 - V199)
INSERT INTO LFA1 (LIFNR, NAME1, LAND1, STCD1, KTOKK)
SELECT 
    'V' || i, 
    'Bulk Vendor ' || i, 
    CASE WHEN i % 5 = 0 THEN 'US' WHEN i % 5 = 1 THEN 'DE' WHEN i % 5 = 2 THEN 'JP' ELSE 'IN' END,
    'TAX-' || i, 
    'KRED'
FROM generate_series(100, 199) i
ON CONFLICT (LIFNR) DO NOTHING;

-- 2. Vendor Company Codes
INSERT INTO LFB1 (LIFNR, BUKRS, AKONT, ZTERM)
SELECT 
    'V' || i, 
    CASE WHEN i % 2 = 0 THEN '1000' ELSE '2000' END, 
    '0021000000', 
    'NT30'
FROM generate_series(100, 199) i
ON CONFLICT (LIFNR, BUKRS) DO NOTHING;

-- 3. Generate 200 Purchase Orders (4500001000 range)
INSERT INTO EKKO (EBELN, BUKRS, LIFNR, BEDAT, WAERS, NETWR)
SELECT 
    CAST(4500001000 + i AS TEXT), 
    CASE WHEN i % 2 = 0 THEN '1000' ELSE '2000' END,
    'V' || (100 + (i % 100)), -- Rotates through the 100 new vendors
    CURRENT_DATE - (i % 30), 
    CASE WHEN i % 3 = 0 THEN 'USD' WHEN i % 3 = 1 THEN 'EUR' ELSE 'INR' END,
    (random() * 10000)::numeric(10,2)
FROM generate_series(1, 200) i
ON CONFLICT (EBELN) DO NOTHING;

-- 4. PO Items (1 item per PO for simplicity)
INSERT INTO EKPO (EBELN, EBELP, MATNR, MENGE, NETPR, WERKS)
SELECT 
    CAST(4500001000 + i AS TEXT), 
    10, 
    'MAT-BULK-' || (i % 10), 
    (random() * 100)::numeric(10,3), 
    (random() * 100)::numeric(10,2), 
    CASE WHEN i % 2 = 0 THEN '1000' ELSE '2000' END
FROM generate_series(1, 200) i
ON CONFLICT (EBELN, EBELP) DO NOTHING;

-- 5. Generate 200 Invoices (INV1000 range) matching the POs
INSERT INTO RBKP (BELNR, GJAHR, BLDAT, BUDAT, LIFNR, XBLNR, WAERS, RMWWR)
SELECT 
    'INV' || (1000 + i), 
    2023, 
    CURRENT_DATE - (i % 30), 
    CURRENT_DATE - (i % 30) + 1, 
    'V' || (100 + (i % 100)), -- Must match PO vendor logic
    'REF-' || (1000 + i), 
    CASE WHEN i % 3 = 0 THEN 'USD' WHEN i % 3 = 1 THEN 'EUR' ELSE 'INR' END,
    -- Introduce variance: 20% of invoices have different amount than PO
    CASE 
        WHEN i % 5 = 0 THEN ((random() * 10000) + 500)::numeric(10,2) -- Intentional variance
        ELSE (random() * 10000)::numeric(10,2) -- Roughly matches (simplified)
    END
FROM generate_series(1, 200) i
ON CONFLICT (BELNR) DO NOTHING;

-- 6. Invoice Items
INSERT INTO RSEG (BELNR, GJAHR, BUZEI, EBELN, EBELP, MATNR, MENGE, WRBTR, BWTAR)
SELECT 
    'INV' || (1000 + i), 
    2023, 
    1, 
    CAST(4500001000 + i AS TEXT), 
    10, 
    'MAT-BULK-' || (i % 10), 
    (random() * 100)::numeric(10,3), 
    -- Match header amount logic
    CASE 
        WHEN i % 5 = 0 THEN ((random() * 10000) + 500)::numeric(10,2) 
        ELSE (random() * 10000)::numeric(10,2) 
    END, 
    ''
FROM generate_series(1, 200) i
ON CONFLICT (BELNR, GJAHR, BUZEI) DO NOTHING;

COMMIT;
