-- SAP Material Master Synthetic Data
-- Generated by Antigravity
-- Adds MARA (General Material Data) and MAKT (Material Descriptions)

BEGIN;

-- 1. Create MARA Table
CREATE TABLE IF NOT EXISTS MARA (
    MATNR VARCHAR(18) PRIMARY KEY, -- Material Number
    MTART VARCHAR(4),              -- Material Type (e.g., ROH, FERT)
    MBRSH VARCHAR(1),              -- Industry Sector
    MATKL VARCHAR(9),              -- Material Group
    MEINS VARCHAR(3),              -- Base Unit of Measure
    NTGEW DECIMAL(13,3),           -- Net Weight
    BRGEW DECIMAL(13,3),           -- Gross Weight
    GEWEI VARCHAR(3)               -- Weight Unit
);

-- 2. Create MAKT Table
CREATE TABLE IF NOT EXISTS MAKT (
    MATNR VARCHAR(18),             -- Material Number
    SPRAS VARCHAR(2),              -- Language Key (EN, DE)
    MAKTX VARCHAR(40),             -- Material Description
    PRIMARY KEY (MATNR, SPRAS)
);

-- 3. Insert Base Materials (used in previous scripts)
INSERT INTO MARA (MATNR, MTART, MBRSH, MATKL, MEINS, NTGEW, BRGEW, GEWEI) VALUES
('MAT-STEEL',  'ROH',  'M', 'METALS', 'KG', 1.000, 1.050, 'KG'),
('MAT-MARLIN', 'HALB', 'M', 'PARTS',  'PC', 0.500, 0.550, 'KG'),
('MAT-CHIP',   'ROH',  'E', 'ELECT',  'PC', 0.010, 0.015, 'KG'),
('MAT-PAPER',  'HILF', 'C', 'OFFICE', 'PC', 0.100, 0.100, 'KG'),
('MAT-SPICE',  'ROH',  'F', 'FOOD',   'KG', 1.000, 1.020, 'KG')
ON CONFLICT (MATNR) DO NOTHING;

INSERT INTO MAKT (MATNR, SPRAS, MAKTX) VALUES
('MAT-STEEL',  'EN', 'High Grade Steel Sheet'),
('MAT-MARLIN', 'EN', 'Marlin Blue Component'),
('MAT-CHIP',   'EN', 'Microcontroller Unit X1'),
('MAT-PAPER',  'EN', 'A4 Premium Paper Ream'),
('MAT-SPICE',  'EN', 'Organic Turmeric Powder')
ON CONFLICT (MATNR, SPRAS) DO NOTHING;

-- 4. Generate Bulk Materials (MAT-BULK-0 to MAT-BULK-9)
INSERT INTO MARA (MATNR, MTART, MBRSH, MATKL, MEINS, NTGEW, BRGEW, GEWEI)
SELECT 
    'MAT-BULK-' || i, 
    'FERT', 
    'M', 
    'GENERAL', 
    'PC', 
    (random() * 10)::numeric(13,3), 
    (random() * 12)::numeric(13,3), 
    'KG'
FROM generate_series(0, 9) i
ON CONFLICT (MATNR) DO NOTHING;

INSERT INTO MAKT (MATNR, SPRAS, MAKTX)
SELECT 
    'MAT-BULK-' || i, 
    'EN', 
    'Generic Bulk Item Type ' || i
FROM generate_series(0, 9) i
ON CONFLICT (MATNR, SPRAS) DO NOTHING;

COMMIT;
