-- SAP Synthetic Data Generation Script (Consolidated)
-- Generated by Antigravity
-- Contains:
-- 1. Base SAP Tables (LFA1, EKKO, RBKP, etc.)
-- 2. Material Master (MARA, MAKT)
-- 3. Expansion Tables (SD, FI, Config - 30+ Total)
-- 4. Analytical Views
-- 5. Synthetic Data (Base + High Volume)

BEGIN;

-- ============================================================================
-- SECTION 1: CORE SAP TABLES (MM/FI)
-- ============================================================================

-- 1. Vendor Master Data (LFA1)
CREATE TABLE IF NOT EXISTS LFA1 (
    LIFNR VARCHAR(10) PRIMARY KEY, -- Vendor Number
    NAME1 VARCHAR(35),             -- Name
    LAND1 CHAR(3),                 -- Country Key
    STCD1 VARCHAR(16),             -- Tax Number
    KTOKK CHAR(4)                  -- Account Group
);

INSERT INTO LFA1 (LIFNR, NAME1, LAND1, STCD1, KTOKK) VALUES
('V001', 'Apex Supply Co', 'US', '12-3456789', 'KRED'),
('V002', 'Global Tech Ltd', 'DE', 'DE123456789', 'KRED'),
('V003', 'Asian Hardware Ltd', 'IN', 'IN987654321', 'KRED'),
('V004', 'Fast Logistics Corp', 'GB', 'GB987654321', 'KRED'),
('V005', 'Quality Parts Supplier', 'FR', 'FR123456789', 'KRED'),
('V006', 'Steel Works GmbH', 'DE', 'DE555666777', 'KRED'),
('V007', 'Marlin Components', 'US', '88-1122334', 'KRED'),
('V008', 'Tokyo Electronics', 'JP', 'JP99887766', 'KRED'),
('V009', 'Paris Supplies', 'FR', 'FR44332211', 'KRED'),
('V010', 'Mumbai Traders', 'IN', 'IN11223344', 'KRED')
ON CONFLICT (LIFNR) DO NOTHING;

-- 2. Vendor Company Code Data (LFB1)
CREATE TABLE IF NOT EXISTS LFB1 (
    LIFNR VARCHAR(10),             -- Vendor Number
    BUKRS CHAR(4),                 -- Company Code
    AKONT VARCHAR(10),             -- Reconciliation Account
    ZTERM CHAR(4),                 -- Payment Terms
    PRIMARY KEY (LIFNR, BUKRS)
);

INSERT INTO LFB1 (LIFNR, BUKRS, AKONT, ZTERM) VALUES
('V001', '1000', '0021000000', 'NT30'),
('V002', '1000', '0021000000', 'NT60'),
('V003', '2000', '0021000000', 'NT45'),
('V004', '1000', '0021000000', 'NT30'),
('V005', '2000', '0021000000', 'NT60'),
('V006', '1000', '0021000000', 'NT30'),
('V007', '1000', '0021000000', 'NT60'),
('V008', '2000', '0021000000', 'NT45'),
('V009', '1000', '0021000000', 'NT30'),
('V010', '2000', '0021000000', 'NT60')
ON CONFLICT (LIFNR, BUKRS) DO NOTHING;

-- 3. Purchase Order Header (EKKO)
CREATE TABLE IF NOT EXISTS EKKO (
    EBELN VARCHAR(10) PRIMARY KEY, -- PO Number
    BUKRS CHAR(4),                 -- Company Code
    LIFNR VARCHAR(10),             -- Vendor
    BEDAT DATE,                    -- PO Date
    WAERS CHAR(5),                 -- Currency
    NETWR NUMERIC(15, 2)           -- Net Value
);

INSERT INTO EKKO (EBELN, BUKRS, LIFNR, BEDAT, WAERS, NETWR) VALUES
('4500000001', '1000', 'V001', '2023-10-01', 'USD', 5000.00),
('4500000002', '1000', 'V002', '2023-10-05', 'EUR', 3000.00),
('4500000003', '2000', 'V003', '2023-10-10', 'INR', 250000.00),
('4500000004', '1000', 'V004', '2023-10-12', 'GBP', 2600.00),
('4500000005', '2000', 'V005', '2023-10-15', 'EUR', 5000.00),
('4500000010', '1000', 'V006', '2023-11-01', 'EUR', 15000.00),
('4500000011', '1000', 'V007', '2023-11-02', 'USD', 8000.00),
('4500000012', '2000', 'V008', '2023-11-03', 'JPY', 1000000.00),
('4500000013', '1000', 'V009', '2023-11-04', 'EUR', 4500.00),
('4500000014', '2000', 'V010', '2023-11-05', 'INR', 500000.00)
ON CONFLICT (EBELN) DO NOTHING;

-- 4. Purchase Order Items (EKPO)
CREATE TABLE IF NOT EXISTS EKPO (
    EBELN VARCHAR(10),             -- PO Number
    EBELP INT,                     -- Item Number
    MATNR VARCHAR(18),             -- Material
    MENGE NUMERIC(13, 3),          -- Quantity
    NETPR NUMERIC(15, 2),          -- Net Price
    WERKS CHAR(4),                 -- Plant
    PRIMARY KEY (EBELN, EBELP)
);

INSERT INTO EKPO (EBELN, EBELP, MATNR, MENGE, NETPR, WERKS) VALUES
('4500000001', 10, 'MAT-1001', 100.000, 50.00, '1000'),
('4500000001', 20, 'MAT-1002', 50.000, 120.00, '1000'),
('4500000002', 10, 'MAT-2001', 200.000, 15.00, '1000'),
('4500000002', 20, 'MAT-2002', 100.000, 20.00, '1000'),
('4500000003', 10, 'MAT-3001', 500.000, 500.00, '2000'),
('4500000003', 20, 'MAT-3002', 200.000, 250.00, '2000'),
('4500000004', 10, 'MAT-1001', 50.000, 52.00, '1000'),
('4500000004', 20, 'MAT-1003', 20.000, 80.00, '1000'),
('4500000005', 10, 'MAT-4001', 20.000, 250.00, '2000'),
('4500000005', 20, 'MAT-4002', 10.000, 100.00, '2000'),
('4500000010', 10, 'MAT-STEEL', 1000.000, 15.00, '1000'),
('4500000011', 10, 'MAT-MARLIN', 200.000, 40.00, '1000'),
('4500000012', 10, 'MAT-CHIP', 5000.000, 200.00, '2000'),
('4500000013', 10, 'MAT-PAPER', 500.000, 9.00, '1000'),
('4500000014', 10, 'MAT-SPICE', 1000.000, 500.00, '2000')
ON CONFLICT (EBELN, EBELP) DO NOTHING;

-- 5. Invoice Document Header (RBKP)
CREATE TABLE IF NOT EXISTS RBKP (
    BELNR VARCHAR(10) PRIMARY KEY, -- Document Number
    GJAHR INT,                     -- Fiscal Year
    BLDAT DATE,                    -- Document Date
    BUDAT DATE,                    -- Posting Date
    LIFNR VARCHAR(10),             -- Vendor Number
    XBLNR VARCHAR(16),             -- Reference
    WAERS CHAR(5),                 -- Currency
    RMWWR NUMERIC(15, 2)           -- Gross Amount
);

INSERT INTO RBKP (BELNR, GJAHR, BLDAT, BUDAT, LIFNR, XBLNR, WAERS, RMWWR) VALUES
('INV0000001', 2023, '2023-10-05', '2023-10-06', 'V001', 'REF-001', 'USD', 11000.00),
('INV0000002', 2023, '2023-10-10', '2023-10-11', 'V002', 'REF-002', 'EUR', 3000.00),
('INV0000003', 2023, '2023-10-15', '2023-10-16', 'V003', 'REF-003', 'INR', 250000.00),
('INV0000004', 2023, '2023-10-18', '2023-10-19', 'V004', 'REF-004', 'GBP', 2600.00),
('INV0000005', 2023, '2023-10-22', '2023-10-23', 'V005', 'REF-005', 'EUR', 5000.00),
('INV0000010', 2023, '2023-11-10', '2023-11-11', 'V006', 'REF-010', 'EUR', 15000.00),
('INV0000011', 2023, '2023-11-12', '2023-11-13', 'V007', 'REF-011', 'USD', 8200.00),
('INV0000012', 2023, '2023-11-15', '2023-11-16', 'V008', 'REF-012', 'JPY', 1000000.00),
('INV0000013', 2023, '2023-11-18', '2023-11-19', 'V009', 'REF-013', 'EUR', 4500.00),
('INV0000014', 2023, '2023-11-20', '2023-11-21', 'V010', 'REF-014', 'INR', 480000.00)
ON CONFLICT (BELNR) DO NOTHING;

-- 6. Invoice Document Line Items (RSEG)
CREATE TABLE IF NOT EXISTS RSEG (
    BELNR VARCHAR(10),             -- Document Number
    GJAHR INT,                     -- Fiscal Year
    BUZEI INT,                     -- Line Item Number
    EBELN VARCHAR(10),             -- PO Number
    EBELP INT,                     -- PO Item Number
    MATNR VARCHAR(18),             -- Material Number
    MENGE NUMERIC(13, 3),          -- Quantity
    WRBTR NUMERIC(15, 2),          -- Amount
    BWTAR VARCHAR(10),             -- Valuation Type
    PRIMARY KEY (BELNR, GJAHR, BUZEI)
);

INSERT INTO RSEG (BELNR, GJAHR, BUZEI, EBELN, EBELP, MATNR, MENGE, WRBTR, BWTAR) VALUES
('INV0000001', 2023, 1, '4500000001', 10, 'MAT-1001', 100.000, 5000.00, ''),
('INV0000001', 2023, 2, '4500000001', 20, 'MAT-1002', 50.000, 6000.00, ''),
('INV0000002', 2023, 1, '4500000002', 10, 'MAT-2001', 200.000, 3000.00, ''),
('INV0000002', 2023, 2, '4500000002', 20, 'MAT-2002', 0.000, 0.00, ''),
('INV0000003', 2023, 1, '4500000003', 10, 'MAT-3001', 500.000, 250000.00, ''),
('INV0000003', 2023, 2, '4500000003', 20, 'MAT-3002', 0.000, 0.00, ''),
('INV0000004', 2023, 1, '4500000004', 10, 'MAT-1001', 50.000, 2600.00, ''),
('INV0000004', 2023, 2, '4500000004', 20, 'MAT-1003', 0.000, 0.00, ''),
('INV0000005', 2023, 1, '4500000005', 10, 'MAT-4001', 20.000, 5000.00, ''),
('INV0000005', 2023, 2, '4500000005', 20, 'MAT-4002', 0.000, 0.00, ''),
('INV0000010', 2023, 1, '4500000010', 10, 'MAT-STEEL', 1000.000, 15000.00, ''),
('INV0000011', 2023, 1, '4500000011', 10, 'MAT-MARLIN', 200.000, 8200.00, ''),
('INV0000012', 2023, 1, '4500000012', 10, 'MAT-CHIP', 5000.000, 1000000.00, ''),
('INV0000013', 2023, 1, '4500000013', 10, 'MAT-PAPER', 500.000, 4500.00, ''),
('INV0000014', 2023, 1, '4500000014', 10, 'MAT-SPICE', 1000.000, 480000.00, '')
ON CONFLICT (BELNR, GJAHR, BUZEI) DO NOTHING;

-- 7. Accounting Document Header (BKPF)
CREATE TABLE IF NOT EXISTS BKPF (
    BUKRS CHAR(4),                 -- Company Code
    BELNR VARCHAR(10),             -- Document Number
    GJAHR INT,                     -- Fiscal Year
    BLART CHAR(2),                 -- Document Type
    BUDAT DATE,                    -- Posting Date
    CPUDT DATE,                    -- Entry Date
    USNAM VARCHAR(12),             -- User Name
    PRIMARY KEY (BUKRS, BELNR, GJAHR)
);

INSERT INTO BKPF (BUKRS, BELNR, GJAHR, BLART, BUDAT, CPUDT, USNAM) VALUES
('1000', '1900000001', 2023, 'RE', '2023-10-06', '2023-10-06', 'JSMITH'),
('1000', '1900000002', 2023, 'RE', '2023-10-11', '2023-10-11', 'ADOE'),
('2000', '1900000003', 2023, 'RE', '2023-10-16', '2023-10-16', 'MWILSON'),
('1000', '1900000004', 2023, 'RE', '2023-10-19', '2023-10-19', 'JSMITH'),
('2000', '1900000005', 2023, 'KR', '2023-10-23', '2023-10-23', 'ADOE')
ON CONFLICT (BUKRS, BELNR, GJAHR) DO NOTHING;

-- 8. Accounting Document Segment (BSEG)
CREATE TABLE IF NOT EXISTS BSEG (
    BUKRS CHAR(4),                 -- Company Code
    BELNR VARCHAR(10),             -- Document Number
    GJAHR INT,                     -- Fiscal Year
    BUZEI INT,                     -- Line Item
    KOART CHAR(1),                 -- Account Type
    SHKZG CHAR(1),                 -- Debit/Credit Indicator
    WRBTR NUMERIC(15, 2),          -- Amount in Document Currency
    DMBTR NUMERIC(15, 2),          -- Amount in Local Currency
    HKONT VARCHAR(10),             -- G/L Account
    KOSTL VARCHAR(10),             -- Cost Center
    PRIMARY KEY (BUKRS, BELNR, GJAHR, BUZEI)
);

INSERT INTO BSEG (BUKRS, BELNR, GJAHR, BUZEI, KOART, SHKZG, WRBTR, DMBTR, HKONT, KOSTL) VALUES
('1000', '1900000001', 2023, 1, 'K', 'H', 11000.00, 11000.00, '0021000000', ''),
('1000', '1900000001', 2023, 2, 'S', 'S', 11000.00, 11000.00, '0063000000', 'CC1000'),
('1000', '1900000002', 2023, 1, 'K', 'H', 3000.00, 3150.00, '0021000000', ''),
('1000', '1900000002', 2023, 2, 'S', 'S', 3000.00, 3150.00, '0063000000', 'CC1000'),
('2000', '1900000003', 2023, 1, 'K', 'H', 250000.00, 2500.00, '0021000000', ''),
('2000', '1900000003', 2023, 2, 'S', 'S', 250000.00, 2500.00, '0063000000', 'CC2000'),
('1000', '1900000004', 2023, 1, 'K', 'H', 2600.00, 2600.00, '0021000000', ''),
('1000', '1900000004', 2023, 2, 'S', 'S', 2600.00, 2600.00, '0063000000', 'CC1000'),
('2000', '1900000005', 2023, 1, 'K', 'H', 5000.00, 6200.00, '0021000000', ''),
('2000', '1900000005', 2023, 2, 'S', 'S', 5000.00, 6200.00, '0063000000', 'CC2000')
ON CONFLICT (BUKRS, BELNR, GJAHR, BUZEI) DO NOTHING;

-- 9. Material Document Header (MKPF)
CREATE TABLE IF NOT EXISTS MKPF (
    MBLNR VARCHAR(10) PRIMARY KEY, -- Material Document Number
    MJAHR INT,                     -- Material Document Year
    BLDAT DATE,                    -- Document Date
    BUDAT DATE,                    -- Posting Date
    USNAM VARCHAR(12)              -- User Name
);

INSERT INTO MKPF (MBLNR, MJAHR, BLDAT, BUDAT, USNAM) VALUES
('5000000001', 2023, '2023-10-03', '2023-10-03', 'JSMITH'),
('5000000002', 2023, '2023-10-08', '2023-10-08', 'ADOE'),
('5000000003', 2023, '2023-10-15', '2023-10-15', 'MWILSON'),
('5000000004', 2023, '2023-10-16', '2023-10-16', 'JSMITH'),
('5000000005', 2023, '2023-10-20', '2023-10-20', 'ADOE')
ON CONFLICT (MBLNR) DO NOTHING;

-- 10. Material Document Items (MSEG)
CREATE TABLE IF NOT EXISTS MSEG (
    MBLNR VARCHAR(10),             -- Material Document Number
    MJAHR INT,                     -- Year
    ZEILE INT,                     -- Item
    MATNR VARCHAR(18),             -- Material
    WERKS CHAR(4),                 -- Plant
    MENGE NUMERIC(13, 3),          -- Quantity
    EBELN VARCHAR(10),             -- PO Reference
    EBELP INT,                     -- PO Item Reference
    PRIMARY KEY (MBLNR, MJAHR, ZEILE)
);

INSERT INTO MSEG (MBLNR, MJAHR, ZEILE, MATNR, WERKS, MENGE, EBELN, EBELP) VALUES
('5000000001', 2023, 1, 'MAT-1001', '1000', 100.000, '4500000001', 10),
('5000000001', 2023, 2, 'MAT-1002', '1000', 50.000, '4500000001', 20),
('5000000002', 2023, 1, 'MAT-2001', '1000', 200.000, '4500000002', 10),
('5000000002', 2023, 2, 'MAT-2002', '1000', 100.000, '4500000002', 20),
('5000000003', 2023, 1, 'MAT-3001', '2000', 500.000, '4500000003', 10),
('5000000003', 2023, 2, 'MAT-3002', '2000', 200.000, '4500000003', 20),
('5000000004', 2023, 1, 'MAT-1001', '1000', 50.000, '4500000004', 10),
('5000000004', 2023, 2, 'MAT-1003', '1000', 20.000, '4500000004', 20),
('5000000005', 2023, 1, 'MAT-4001', '2000', 20.000, '4500000005', 10),
('5000000005', 2023, 2, 'MAT-4002', '2000', 10.000, '4500000005', 20)
ON CONFLICT (MBLNR, MJAHR, ZEILE) DO NOTHING;


-- ============================================================================
-- SECTION 2: MATERIAL MASTER & EXPANSION TABLES (SD, FI, CONFIG)
-- ============================================================================

-- MARA: Material Master General
CREATE TABLE IF NOT EXISTS MARA (
    MATNR VARCHAR(18) PRIMARY KEY, -- Material Number
    MTART VARCHAR(4),              -- Material Type (e.g., ROH, FERT)
    MBRSH VARCHAR(1),              -- Industry Sector
    MATKL VARCHAR(9),              -- Material Group
    MEINS VARCHAR(3),              -- Base Unit of Measure
    NTGEW DECIMAL(13,3),           -- Net Weight
    BRGEW DECIMAL(13,3),           -- Gross Weight
    GEWEI VARCHAR(3)               -- Weight Unit
);
INSERT INTO MARA (MATNR, MTART, MBRSH, MATKL, MEINS, NTGEW, BRGEW, GEWEI) VALUES
('MAT-STEEL',  'ROH',  'M', 'METALS', 'KG', 1.000, 1.050, 'KG'),
('MAT-MARLIN', 'HALB', 'M', 'PARTS',  'PC', 0.500, 0.550, 'KG'),
('MAT-CHIP',   'ROH',  'E', 'ELECT',  'PC', 0.010, 0.015, 'KG'),
('MAT-PAPER',  'HILF', 'C', 'OFFICE', 'PC', 0.100, 0.100, 'KG'),
('MAT-SPICE',  'ROH',  'F', 'FOOD',   'KG', 1.000, 1.020, 'KG')
ON CONFLICT (MATNR) DO NOTHING;

-- MAKT: Material Descriptions
CREATE TABLE IF NOT EXISTS MAKT (
    MATNR VARCHAR(18),             -- Material Number
    SPRAS VARCHAR(2),              -- Language Key (EN, DE)
    MAKTX VARCHAR(40),             -- Material Description
    PRIMARY KEY (MATNR, SPRAS)
);
INSERT INTO MAKT (MATNR, SPRAS, MAKTX) VALUES
('MAT-STEEL',  'EN', 'High Grade Steel Sheet'),
('MAT-MARLIN', 'EN', 'Marlin Blue Component'),
('MAT-CHIP',   'EN', 'Microcontroller Unit X1'),
('MAT-PAPER',  'EN', 'A4 Premium Paper Ream'),
('MAT-SPICE',  'EN', 'Organic Turmeric Powder')
ON CONFLICT (MATNR, SPRAS) DO NOTHING;

-- T001: Company Codes
CREATE TABLE IF NOT EXISTS T001 (
    BUKRS VARCHAR(4) PRIMARY KEY,
    BUTXT VARCHAR(25),
    ORT01 VARCHAR(25),
    LAND1 VARCHAR(3)
);
INSERT INTO T001 (BUKRS, BUTXT, ORT01, LAND1) VALUES
('1000', 'TranAI Global HQ', 'Berlin', 'DE'),
('2000', 'TranAI Americas', 'New York', 'US'),
('3000', 'TranAI Asia', 'Tokyo', 'JP'),
('4000', 'TranAI India', 'Bangalore', 'IN')
ON CONFLICT (BUKRS) DO NOTHING;

-- T001W: Plants
CREATE TABLE IF NOT EXISTS T001W (
    WERKS VARCHAR(4) PRIMARY KEY,
    NAME1 VARCHAR(30),
    STRAS VARCHAR(30),
    ORT01 VARCHAR(25)
);
INSERT INTO T001W (WERKS, NAME1, STRAS, ORT01) VALUES
('1000', 'Berlin Plant', 'Main St 1', 'Berlin'),
('1100', 'Hamburg Warehouse', 'Port Rd 5', 'Hamburg'),
('2000', 'NY Distribution', '5th Ave', 'New York'),
('3000', 'Tokyo Mfg', 'Shibuya 1', 'Tokyo')
ON CONFLICT (WERKS) DO NOTHING;

-- T002: Languages
CREATE TABLE IF NOT EXISTS T002 (
    SPRAS VARCHAR(2) PRIMARY KEY,
    SPTXT VARCHAR(20)
);
INSERT INTO T002 (SPRAS, SPTXT) VALUES
('EN', 'English'),
('DE', 'German'),
('FR', 'French'),
('JP', 'Japanese')
ON CONFLICT (SPRAS) DO NOTHING;

-- TCURC: Currencies
CREATE TABLE IF NOT EXISTS TCURC (
    WAERS VARCHAR(5) PRIMARY KEY,
    LTEXT VARCHAR(40)
);
INSERT INTO TCURC (WAERS, LTEXT) VALUES
('EUR', 'Euro'),
('USD', 'US Dollar'),
('JPY', 'Japanese Yen'),
('INR', 'Indian Rupee')
ON CONFLICT (WAERS) DO NOTHING;

-- KNA1: Customer Master
CREATE TABLE IF NOT EXISTS KNA1 (
    KUNNR VARCHAR(10) PRIMARY KEY,
    NAME1 VARCHAR(35),
    ORT01 VARCHAR(35),
    LAND1 VARCHAR(3)
);
INSERT INTO KNA1 (KUNNR, NAME1, ORT01, LAND1) VALUES
('C001', 'Tech Corp', 'San Francisco', 'US'),
('C002', 'Auto Motto', 'Stuttgart', 'DE'),
('C003', 'Fast Retail', 'London', 'UK'),
('C004', 'Green Energy', 'Oslo', 'NO')
ON CONFLICT (KUNNR) DO NOTHING;

-- KNB1: Customer Company Data
CREATE TABLE IF NOT EXISTS KNB1 (
    KUNNR VARCHAR(10),
    BUKRS VARCHAR(4),
    AKONT VARCHAR(10),
    PRIMARY KEY (KUNNR, BUKRS)
);
INSERT INTO KNB1 (KUNNR, BUKRS, AKONT) VALUES
('C001', '2000', '140000'),
('C002', '1000', '140000'),
('C003', '1000', '140000')
ON CONFLICT (KUNNR, BUKRS) DO NOTHING;

-- VBAK: Sales Order Header
CREATE TABLE IF NOT EXISTS VBAK (
    VBELN VARCHAR(10) PRIMARY KEY,
    ERDAT DATE,
    ERNAM VARCHAR(12),
    KUNNR VARCHAR(10),
    NETWR DECIMAL(15,2),
    WAERS VARCHAR(5)
);
INSERT INTO VBAK (VBELN, ERDAT, ERNAM, KUNNR, NETWR, WAERS) VALUES
('SO00001', '2023-11-01', 'USER1', 'C001', 5000.00, 'USD'),
('SO00002', '2023-11-05', 'USER2', 'C002', 12000.00, 'EUR'),
('SO00003', '2023-11-10', 'USER1', 'C001', 3500.00, 'USD')
ON CONFLICT (VBELN) DO NOTHING;

-- VBAP: Sales Order Item
CREATE TABLE IF NOT EXISTS VBAP (
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    KWMENG DECIMAL(15,3),
    NETWR DECIMAL(15,2),
    PRIMARY KEY (VBELN, POSNR)
);
INSERT INTO VBAP (VBELN, POSNR, MATNR, KWMENG, NETWR) VALUES
('SO00001', '10', 'MAT-MARLIN', 100, 4000.00),
('SO00001', '20', 'MAT-CHIP', 50, 1000.00),
('SO00002', '10', 'MAT-STEEL', 200, 12000.00)
ON CONFLICT (VBELN, POSNR) DO NOTHING;

-- LIKP: Delivery Header
CREATE TABLE IF NOT EXISTS LIKP (
    VBELN VARCHAR(10) PRIMARY KEY,
    ERDAT DATE,
    LIFEX VARCHAR(35)
);
INSERT INTO LIKP (VBELN, ERDAT, LIFEX) VALUES
('DL00001', '2023-11-03', 'EXT-123'),
('DL00002', '2023-11-08', 'EXT-456')
ON CONFLICT (VBELN) DO NOTHING;

-- LIPS: Delivery Item
CREATE TABLE IF NOT EXISTS LIPS (
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    MATNR VARCHAR(18),
    LFIMG DECIMAL(13,3),
    PRIMARY KEY (VBELN, POSNR)
);
INSERT INTO LIPS (VBELN, POSNR, MATNR, LFIMG) VALUES
('DL00001', '10', 'MAT-MARLIN', 100),
('DL00002', '10', 'MAT-STEEL', 200)
ON CONFLICT (VBELN, POSNR) DO NOTHING;

-- VBRK: Billing Header
CREATE TABLE IF NOT EXISTS VBRK (
    VBELN VARCHAR(10) PRIMARY KEY,
    FKDAT DATE,
    NETWR DECIMAL(15,2),
    KUNAG VARCHAR(10)
);
INSERT INTO VBRK (VBELN, FKDAT, NETWR, KUNAG) VALUES
('BILL001', '2023-11-04', 5000.00, 'C001'),
('BILL002', '2023-11-09', 12000.00, 'C002')
ON CONFLICT (VBELN) DO NOTHING;

-- VBRP: Billing Item
CREATE TABLE IF NOT EXISTS VBRP (
    VBELN VARCHAR(10),
    POSNR VARCHAR(6),
    AUBEL VARCHAR(10),
    AUPOS VARCHAR(6),
    NETWR DECIMAL(15,2),
    PRIMARY KEY (VBELN, POSNR)
);
INSERT INTO VBRP (VBELN, POSNR, AUBEL, AUPOS, NETWR) VALUES
('BILL001', '10', 'SO00001', '10', 4000.00),
('BILL001', '20', 'SO00001', '20', 1000.00),
('BILL002', '10', 'SO00002', '10', 12000.00)
ON CONFLICT (VBELN, POSNR) DO NOTHING;

-- CSKS: Cost Centers
CREATE TABLE IF NOT EXISTS CSKS (
    KOSTL VARCHAR(10) PRIMARY KEY,
    DATBI DATE,
    KOKRS VARCHAR(4),
    BUKRS VARCHAR(4)
);
INSERT INTO CSKS (KOSTL, DATBI, KOKRS, BUKRS) VALUES
('CC100', '9999-12-31', '1000', '1000'),
('CC200', '9999-12-31', '1000', '1000'),
('CC300', '9999-12-31', '2000', '2000')
ON CONFLICT (KOSTL) DO NOTHING;

-- CSKT: Cost Center Texts
CREATE TABLE IF NOT EXISTS CSKT (
    KOSTL VARCHAR(10),
    SPRAS VARCHAR(2),
    LTEXT VARCHAR(40),
    PRIMARY KEY (KOSTL, SPRAS)
);
INSERT INTO CSKT (KOSTL, SPRAS, LTEXT) VALUES
('CC100', 'EN', 'IT Department'),
('CC200', 'EN', 'HR Department'),
('CC300', 'EN', 'Sales Department')
ON CONFLICT (KOSTL, SPRAS) DO NOTHING;

-- PRPS: WBS Elements
CREATE TABLE IF NOT EXISTS PRPS (
    PSPNR VARCHAR(8) PRIMARY KEY,
    POST1 VARCHAR(40),
    PSTART DATE,
    PENDE DATE
);
INSERT INTO PRPS (PSPNR, POST1, PSTART, PENDE) VALUES
('WBS-01', 'New Office Build', '2023-01-01', '2023-12-31'),
('WBS-02', 'SAP Implementation', '2023-06-01', '2024-06-01')
ON CONFLICT (PSPNR) DO NOTHING;


-- ============================================================================
-- SECTION 3: TOOL COMPARISON TABLES
-- ============================================================================

CREATE TABLE IF NOT EXISTS tool_cost_comparison (
    id SERIAL PRIMARY KEY,
    cost_category VARCHAR(50),
    sap_datasphere VARCHAR(30),
    microsoft_fabric VARCHAR(30),
    informatica_idmc VARCHAR(30),
    airbyte_self_hosted VARCHAR(30),
    airbyte_cloud VARCHAR(30)
);

INSERT INTO tool_cost_comparison (cost_category, sap_datasphere, microsoft_fabric, informatica_idmc, airbyte_self_hosted, airbyte_cloud) VALUES
('Annual License', '$40,000', '$96,000 (F64)', '$60,000 (500 IPU)', '$0 (Open Source)', '$30,000'),
('SAP Connector', 'Included', 'Included', '$25,000', 'DIY', 'DIY'),
('CDC/SLT License', '$20,000', 'Included', '$15,000', 'N/A', 'N/A'),
('Storage', '$6,000 (500GB)', 'Included (2TB)', '$6,000 (5TB)', '$600 (500GB EBS)', 'Included'),
('Compute/Infrastructure', '$12,000', 'Included', 'Included', '$6,000 (EC2)', 'Included'),
('Data Transfer', 'Included', 'Included', 'Included', '$1,200', 'Included'),
('Monitoring', 'Included', 'Included', 'Included', '$600', 'Included'),
('Support', '$15,600 (20%)', 'Included', '$21,000', '$0', 'Included'),
('Total Annual (Recurring)', '$93,600', '$100,800', '$127,000', '$8,400', '$30,000'),
('Implementation/Setup', '$30,000', '$20,000', '$40,000', '$0', '$0'),
('Custom Development', '$15,000', '$15,000', '$50,000', '$40,000', '$40,000'),
('Testing & Validation', '$10,000', '$8,000', '$15,000', '$10,000', '$10,000'),
('Training', '$5,000', '$5,000', '$15,000', '$5,000', '$0'),
('Total One-Time', '$60,000', '$48,000', '$140,000', '$55,000', '$50,000'),
('Ongoing Maintenance', 'Included', 'Included', 'Included', '$40,000/year', 'Included'),
('TOTAL YEAR 1', '$153,600', '$148,800', '$267,000', '$103,400', '$70,000'),
('TOTAL YEAR 2', '$93,600', '$100,800', '$127,000', '$48,400', '$30,000'),
('TOTAL YEAR 3', '$93,600', '$100,800', '$127,000', '$48,400', '$30,000'),
('3-Year TCO', '$340,800', '$350,400', '$521,000', '$200,200', '$130,000');


CREATE TABLE IF NOT EXISTS tool_performance_metrics (
    id SERIAL PRIMARY KEY,
    performance_metric VARCHAR(80),
    sap_datasphere VARCHAR(50),
    microsoft_fabric VARCHAR(50),
    informatica_idmc VARCHAR(50),
    airbyte VARCHAR(50)
);

INSERT INTO tool_performance_metrics (performance_metric, sap_datasphere, microsoft_fabric, informatica_idmc, airbyte) VALUES
('Real-Time Capability', 'Yes (CDC)', 'Near Real-Time', 'Yes (CDC)', 'Batch Only'),
('Average Latency', '30 sec - 2 min', '2 - 5 min', '1 - 3 min', '10 - 20 min'),
('Best Case Latency', '30 seconds', '2 minutes', '1 minute', '10 minutes'),
('P95 Latency', '2 minutes', '5 minutes', '3 minutes', '30 minutes'),
('Extraction Method', 'Log-based CDC', 'Polling (RFC)', 'Log-based CDC', 'Polling (RFC)'),
('Minimum Sync Interval', 'Continuous', '1-2 min (practical: 5 min)', 'Continuous', '10 minutes'),
('Initial Load - RBKP (1M records)', '15-30 minutes', '45-60 minutes', '20-30 minutes', '2-4 hours'),
('Initial Load - RSEG (5M records)', '1-2 hours', '3-4 hours', '1.5-2 hours', '10-15 hours'),
('Initial Load - BKPF (10M records)', '2-4 hours', '6-8 hours', '2-3 hours', '20-30 hours'),
('Initial Load - Total Time', '4-8 hours', '10-15 hours', '6-10 hours', '30-50 hours'),
('Incremental Throughput', '5,000-10,000/min', '1,000-3,000/min', '10,000-20,000/min', '500-1,000/min'),
('Max Daily Volume', '10M+ records', '5M records', '50M+ records', '1M records'),
('Parallel Processing', 'Automatic', 'Configurable', 'Up to 64 threads', 'Manual coding'),
('Network Bandwidth', '10-50 Mbps', '5-20 Mbps', '20-100 Mbps', '5-10 Mbps'),
('Network Latency Tolerance', '<50ms', '<100ms', '<30ms', '<200ms'),
('SLA Uptime', '99.5%', '99.9%', '99.95%', '99.0% (self-managed)');


CREATE TABLE IF NOT EXISTS tool_summary (
    tool_name VARCHAR(50),
    vendor VARCHAR(50),
    extraction_method VARCHAR(50),
    year1_cost VARCHAR(20),
    year1_cost_numeric INT,
    cdc_capable BOOLEAN,
    recommended_for VARCHAR(100)
);

INSERT INTO tool_summary (tool_name, vendor, extraction_method, year1_cost, year1_cost_numeric, cdc_capable, recommended_for) VALUES
('SAP Datasphere', 'SAP', 'SLT Log-based CDC', '$153,600', 153600, TRUE, 'SAP-native, <2 min latency needed'),
('Microsoft Fabric', 'Microsoft', 'Polling via RFC (ADF)', '$148,800', 148800, FALSE, 'Best cost/performance, 2-5 min latency OK'),
('Informatica IDMC', 'Informatica', 'Log-based CDC / PowerCenter', '$267,000', 267000, TRUE, '>50K invoices/day, multi-SAP systems'),
('Airbyte (Self-Hosted)', 'Airbyte OSS', 'Polling (custom PyRFC)', '$103,400', 103400, FALSE, 'Low budget, high engineering capacity'),
('Airbyte (Cloud)', 'Airbyte', 'Polling (custom PyRFC)', '$70,000', 70000, FALSE, 'Lowest TCO, accept 10-20 min latency');


-- ============================================================================
-- SECTION 4: HIGH VOLUME & ANALYTICS
-- ============================================================================

-- High Volume Data (100 Vendors, 200 POs, 200 Invoices)
INSERT INTO LFA1 (LIFNR, NAME1, LAND1, STCD1, KTOKK)
SELECT 'V' || i, 'Bulk Vendor ' || i, 'US', 'TAX-' || i, 'KRED'
FROM generate_series(100, 199) i ON CONFLICT (LIFNR) DO NOTHING;

INSERT INTO LFB1 (LIFNR, BUKRS, AKONT, ZTERM)
SELECT 'V' || i, '1000', '0021000000', 'NT30'
FROM generate_series(100, 199) i ON CONFLICT (LIFNR, BUKRS) DO NOTHING;

INSERT INTO EKKO (EBELN, BUKRS, LIFNR, BEDAT, WAERS, NETWR)
SELECT CAST(4500001000 + i AS TEXT), '1000', 'V' || (100 + (i % 100)), CURRENT_DATE - (i % 30), 'USD', (random() * 10000)::numeric(10,2)
FROM generate_series(1, 200) i ON CONFLICT (EBELN) DO NOTHING;

INSERT INTO EKPO (EBELN, EBELP, MATNR, MENGE, NETPR, WERKS)
SELECT CAST(4500001000 + i AS TEXT), 10, 'MAT-BULK-' || (i % 10), (random() * 100)::numeric(10,3), (random() * 100)::numeric(10,2), '1000'
FROM generate_series(1, 200) i ON CONFLICT (EBELN, EBELP) DO NOTHING;

INSERT INTO RBKP (BELNR, GJAHR, BLDAT, BUDAT, LIFNR, XBLNR, WAERS, RMWWR)
SELECT 'INV' || (1000 + i), 2023, CURRENT_DATE - (i % 30), CURRENT_DATE - (i % 30) + 1, 'V' || (100 + (i % 100)), 'REF-' || (1000 + i), 'USD', (random() * 10000)::numeric(10,2)
FROM generate_series(1, 200) i ON CONFLICT (BELNR) DO NOTHING;

INSERT INTO RSEG (BELNR, GJAHR, BUZEI, EBELN, EBELP, MATNR, MENGE, WRBTR, BWTAR)
SELECT 'INV' || (1000 + i), 2023, 1, CAST(4500001000 + i AS TEXT), 10, 'MAT-BULK-' || (i % 10), (random() * 100)::numeric(10,3), (random() * 100)::numeric(10,2), ''
FROM generate_series(1, 200) i ON CONFLICT (BELNR, GJAHR, BUZEI) DO NOTHING;

INSERT INTO MARA (MATNR, MTART, MBRSH, MATKL, MEINS, NTGEW, BRGEW, GEWEI)
SELECT 'MAT-BULK-' || i, 'FERT', 'M', 'GENERAL', 'PC', (random() * 10)::numeric(13,3), (random() * 12)::numeric(13,3), 'KG'
FROM generate_series(0, 9) i ON CONFLICT (MATNR) DO NOTHING;

INSERT INTO MAKT (MATNR, SPRAS, MAKTX)
SELECT 'MAT-BULK-' || i, 'EN', 'Generic Bulk Item Type ' || i
FROM generate_series(0, 9) i ON CONFLICT (MATNR, SPRAS) DO NOTHING;

-- Analytics Views
CREATE OR REPLACE VIEW v_vendor_spend_analysis AS
SELECT l.lifnr, l.name1, l.land1, COUNT(r.belnr) AS invoice_count, SUM(r.rmwwr) AS total_spend, AVG(r.rmwwr) AS avg_invoice_amount, r.waers
FROM lfa1 l JOIN rbkp r ON l.lifnr = r.lifnr GROUP BY l.lifnr, l.name1, l.land1, r.waers;

CREATE OR REPLACE VIEW v_po_vs_invoice_variance AS
SELECT rs.belnr AS invoice_doc, rs.buzei AS invoice_item, rs.ebeln AS po_number, rs.ebelp AS po_item, rs.matnr, rs.menge AS invoice_qty, rs.wrbtr AS invoice_amount, (ek.netpr * rs.menge) AS expected_po_amount, (rs.wrbtr - (ek.netpr * rs.menge)) AS variance_amount, CASE WHEN (rs.wrbtr - (ek.netpr * rs.menge)) > 0 THEN 'Overbilled' WHEN (rs.wrbtr - (ek.netpr * rs.menge)) < 0 THEN 'Underbilled' ELSE 'Match' END AS status
FROM rseg rs JOIN ekpo ek ON rs.ebeln = ek.ebeln AND rs.ebelp = ek.ebelp;

COMMIT;
