-- SAP Analytics Views
-- Generated by Antigravity

BEGIN;

-- 1. Vendor Spend Analysis View
-- Shows total spend, invoice count, and average invoice amount per vendor
CREATE OR REPLACE VIEW v_vendor_spend_analysis AS
SELECT 
    l.lifnr,
    l.name1,
    l.land1,
    COUNT(r.belnr) AS invoice_count,
    SUM(r.rmwwr) AS total_spend,
    AVG(r.rmwwr) AS avg_invoice_amount,
    r.waers
FROM lfa1 l
JOIN rbkp r ON l.lifnr = r.lifnr
GROUP BY l.lifnr, l.name1, l.land1, r.waers;

-- 2. PO vs Invoice Variance View
-- Identifies line items where invoice amount differs from PO net price * quantity
-- (Simplified variance logic: Invoice Amount vs (PO Unit Price * Invoice Qty))
CREATE OR REPLACE VIEW v_po_vs_invoice_variance AS
SELECT 
    rs.belnr AS invoice_doc,
    rs.buzei AS invoice_item,
    rs.ebeln AS po_number,
    rs.ebelp AS po_item,
    rs.matnr,
    rs.menge AS invoice_qty,
    rs.wrbtr AS invoice_amount,
    (ek.netpr * rs.menge) AS expected_po_amount,
    (rs.wrbtr - (ek.netpr * rs.menge)) AS variance_amount,
    CASE 
        WHEN (rs.wrbtr - (ek.netpr * rs.menge)) > 0 THEN 'Overbilled'
        WHEN (rs.wrbtr - (ek.netpr * rs.menge)) < 0 THEN 'Underbilled'
        ELSE 'Match'
    END AS status
FROM rseg rs
JOIN ekpo ek ON rs.ebeln = ek.ebeln AND rs.ebelp = ek.ebelp;

-- 3. Tool ROI Analysis View
-- Combines Cost and Performance (Logic: Cost per 1M records processed)
-- Note: 'performance_metric' names must match exactly for join logic or rely on row ID correlations (simplified here).
-- Creating a simple comparative view instead:
CREATE OR REPLACE VIEW v_tool_comparison_matrix AS
SELECT 
    s.tool_name,
    s.vendor,
    s.year1_cost,
    s.year1_cost_numeric,
    s.cdc_capable,
    pm.sap_datasphere AS latency_metric
FROM tool_summary s
CROSS JOIN (SELECT sap_datasphere FROM tool_performance_metrics WHERE performance_metric = 'Average Latency') pm
WHERE s.tool_name = 'SAP Datasphere'
UNION ALL
SELECT 
    s.tool_name,
    s.vendor,
    s.year1_cost,
    s.year1_cost_numeric,
    s.cdc_capable,
    pm.microsoft_fabric AS latency_metric
FROM tool_summary s
CROSS JOIN (SELECT microsoft_fabric FROM tool_performance_metrics WHERE performance_metric = 'Average Latency') pm
WHERE s.tool_name = 'Microsoft Fabric';

COMMIT;
