"""Initial migration

Revision ID: 46d01bf50bef
Revises: 
Create Date: 2026-02-24 14:52:01.013599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46d01bf50bef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_promoted_purchase_orders_updated_at', table_name='promoted_purchase_orders', schema='ai')
    op.drop_table('promoted_purchase_orders', schema='ai')
    op.drop_index('idx_promoted_vendors_updated_at', table_name='promoted_vendors', schema='ai')
    op.drop_table('promoted_vendors', schema='ai')
    op.drop_index('ix_ai_synthetic_data_id', table_name='synthetic_data', schema='ai')
    op.drop_table('synthetic_data', schema='ai')
    op.drop_table('ai_invoices', schema='ai')
    op.drop_index('idx_promoted_inventory_updated_at', table_name='promoted_inventory', schema='ai')
    op.drop_table('promoted_inventory', schema='ai')
    op.drop_index('ix_ai_users_id', table_name='users', schema='ai')
    op.drop_table('users', schema='ai')
    op.drop_table('_sync_state', schema='ai')
    op.drop_table('ai_vendors', schema='ai')
    op.drop_index('idx_promoted_invoices_updated_at', table_name='promoted_invoices', schema='ai')
    op.drop_table('promoted_invoices', schema='ai')
    op.alter_column('bkpf', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Company Code',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bkpf', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Accounting Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bkpf', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bkpf', 'BLDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'WAERS',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Currency Key',
               existing_nullable=True,
               schema='sap')
    op.drop_column('bkpf', 'TCODE', schema='sap')
    op.drop_column('bkpf', 'USNAM', schema='sap')
    op.drop_column('bkpf', 'BVORG', schema='sap')
    op.drop_column('bkpf', 'MONAT', schema='sap')
    op.drop_column('bkpf', 'BKTXT', schema='sap')
    op.drop_column('bkpf', 'CPUDT', schema='sap')
    op.drop_column('bkpf', 'DBBLG', schema='sap')
    op.drop_column('bkpf', 'KURSF', schema='sap')
    op.drop_column('bkpf', 'STJAH', schema='sap')
    op.drop_column('bkpf', 'WWERT', schema='sap')
    op.drop_column('bkpf', 'BLART', schema='sap')
    op.drop_column('bkpf', 'created_at', schema='sap')
    op.drop_column('bkpf', 'KZWRS', schema='sap')
    op.drop_column('bkpf', 'AEDAT', schema='sap')
    op.drop_column('bkpf', 'UPDDT', schema='sap')
    op.drop_column('bkpf', 'STBLG', schema='sap')
    op.drop_column('bkpf', 'CPUTM', schema='sap')
    op.drop_column('bkpf', 'XBLNR', schema='sap')
    op.alter_column('bseg', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Company Code',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Accounting Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'BUZEI',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='Line Item Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'DMBTR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Amount in Local Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bseg', 'WRBTR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bseg', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Account Number of Vendor or Creditor',
               existing_nullable=True,
               schema='sap')
    op.drop_column('bseg', 'UMSKZ', schema='sap')
    op.drop_column('bseg', 'MWSTS', schema='sap')
    op.drop_column('bseg', 'KUNNR', schema='sap')
    op.drop_column('bseg', 'BZIRK', schema='sap')
    op.drop_column('bseg', 'KOSTL', schema='sap')
    op.drop_column('bseg', 'HWZUZ', schema='sap')
    op.drop_column('bseg', 'FWBAS', schema='sap')
    op.drop_column('bseg', 'KOART', schema='sap')
    op.drop_column('bseg', 'PARGB', schema='sap')
    op.drop_column('bseg', 'AUFNR', schema='sap')
    op.drop_column('bseg', 'created_at', schema='sap')
    op.drop_column('bseg', 'HKONT', schema='sap')
    op.drop_column('bseg', 'MWSKZ', schema='sap')
    op.drop_column('bseg', 'SHKZG', schema='sap')
    op.drop_column('bseg', 'BSCHL', schema='sap')
    op.drop_column('bseg', 'PROJK', schema='sap')
    op.drop_column('bseg', 'HWBAS', schema='sap')
    op.drop_column('bseg', 'GSBER', schema='sap')
    op.drop_column('bseg', 'FWZUZ', schema='sap')
    op.drop_column('bseg', 'WMWST', schema='sap')
    op.alter_column('ekko', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Purchasing Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekko', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Company Code',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'AEDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date on Which Record Was Created',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Vendor Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'WAERS',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Currency Key',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'NETWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Net Order Value',
               existing_nullable=True,
               schema='sap')
    op.drop_column('ekko', 'ZBD1T', schema='sap')
    op.drop_column('ekko', 'LOEKZ', schema='sap')
    op.drop_column('ekko', 'BSART', schema='sap')
    op.drop_column('ekko', 'BEDAT', schema='sap')
    op.drop_column('ekko', 'KUFIX', schema='sap')
    op.drop_column('ekko', 'EKORG', schema='sap')
    op.drop_column('ekko', 'ZBD2P', schema='sap')
    op.drop_column('ekko', 'KDATB', schema='sap')
    op.drop_column('ekko', 'KNUMV', schema='sap')
    op.drop_column('ekko', 'ZBD2T', schema='sap')
    op.drop_column('ekko', 'BWVKO', schema='sap')
    op.drop_column('ekko', 'BSAKU', schema='sap')
    op.drop_column('ekko', 'RESWK', schema='sap')
    op.drop_column('ekko', 'LPNOH', schema='sap')
    op.drop_column('ekko', 'STATU', schema='sap')
    op.drop_column('ekko', 'KDATE', schema='sap')
    op.drop_column('ekko', 'EKGRP', schema='sap')
    op.drop_column('ekko', 'created_at', schema='sap')
    op.drop_column('ekko', 'WKURS', schema='sap')
    op.drop_column('ekko', 'LIBRE', schema='sap')
    op.drop_column('ekko', 'ZBD3T', schema='sap')
    op.drop_column('ekko', 'PROCSTAT', schema='sap')
    op.drop_column('ekko', 'ZTERM', schema='sap')
    op.drop_column('ekko', 'BSTYP', schema='sap')
    op.drop_column('ekko', 'ERNAM', schema='sap')
    op.drop_column('ekko', 'ZBD1P', schema='sap')
    op.alter_column('ekpo', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Purchasing Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekpo', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Item Number of Purchasing Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekpo', 'MATNR',
               existing_type=sa.VARCHAR(length=18),
               comment=None,
               existing_comment='Material Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'MENGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Purchase Order Quantity',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'NETPR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Net Price in Purchasing Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'NETWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Net Order Value in PO Currency',
               existing_nullable=True,
               schema='sap')
    op.drop_column('ekpo', 'LGORT', schema='sap')
    op.drop_column('ekpo', 'BPUMN', schema='sap')
    op.drop_column('ekpo', 'LOEKZ', schema='sap')
    op.drop_column('ekpo', 'MEINS', schema='sap')
    op.drop_column('ekpo', 'TXZ01', schema='sap')
    op.drop_column('ekpo', 'BUKRS', schema='sap')
    op.drop_column('ekpo', 'BWTAR', schema='sap')
    op.drop_column('ekpo', 'EMATN', schema='sap')
    op.drop_column('ekpo', 'MATKL', schema='sap')
    op.drop_column('ekpo', 'WEBAZ', schema='sap')
    op.drop_column('ekpo', 'ABSKZ', schema='sap')
    op.drop_column('ekpo', 'INSMK', schema='sap')
    op.drop_column('ekpo', 'SPINF', schema='sap')
    op.drop_column('ekpo', 'WERKS', schema='sap')
    op.drop_column('ekpo', 'STATU', schema='sap')
    op.drop_column('ekpo', 'PEINH', schema='sap')
    op.drop_column('ekpo', 'PRSDR', schema='sap')
    op.drop_column('ekpo', 'created_at', schema='sap')
    op.drop_column('ekpo', 'BWTTY', schema='sap')
    op.drop_column('ekpo', 'AEDAT', schema='sap')
    op.drop_column('ekpo', 'BRTWR', schema='sap')
    op.drop_column('ekpo', 'MWSKZ', schema='sap')
    op.drop_column('ekpo', 'BPUMZ', schema='sap')
    op.drop_column('ekpo', 'BONUS', schema='sap')
    op.drop_column('ekpo', 'BEDNR', schema='sap')
    op.drop_column('ekpo', 'AGDAT', schema='sap')
    op.alter_column('lfa1', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Vendor Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('lfa1', 'NAME1',
               existing_type=sa.VARCHAR(length=35),
               comment=None,
               existing_comment='Name 1',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'COUNTRY',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='Country Key',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'ERDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date on which record was created',
               existing_nullable=True,
               schema='sap')
    op.drop_column('lfa1', 'KTOKK', schema='sap')
    op.drop_column('lfa1', 'NAME2', schema='sap')
    op.drop_column('lfa1', 'CITY1', schema='sap')
    op.drop_column('lfa1', 'VBUND', schema='sap')
    op.drop_column('lfa1', 'UPTIM', schema='sap')
    op.drop_column('lfa1', 'MBRSH', schema='sap')
    op.drop_column('lfa1', 'FISKN', schema='sap')
    op.drop_column('lfa1', 'TELF2', schema='sap')
    op.drop_column('lfa1', 'STCD2', schema='sap')
    op.drop_column('lfa1', 'SPERR', schema='sap')
    op.drop_column('lfa1', 'TELFX', schema='sap')
    op.drop_column('lfa1', 'UPDAT', schema='sap')
    op.drop_column('lfa1', 'POST_CODE1', schema='sap')
    op.drop_column('lfa1', 'LOEVM', schema='sap')
    op.drop_column('lfa1', 'STCD3', schema='sap')
    op.drop_column('lfa1', 'TELTX', schema='sap')
    op.drop_column('lfa1', 'TELF1', schema='sap')
    op.drop_column('lfa1', 'TELX1', schema='sap')
    op.drop_column('lfa1', 'SPERZ', schema='sap')
    op.drop_column('lfa1', 'REGION', schema='sap')
    op.drop_column('lfa1', 'STCEG', schema='sap')
    op.drop_column('lfa1', 'NAME3', schema='sap')
    op.drop_column('lfa1', 'KONZS', schema='sap')
    op.drop_column('lfa1', 'created_at', schema='sap')
    op.drop_column('lfa1', 'NAME4', schema='sap')
    op.drop_column('lfa1', 'STCD1', schema='sap')
    op.drop_column('lfa1', 'ERNAM', schema='sap')
    op.drop_column('lfa1', 'LANGU', schema='sap')
    op.drop_column('lfa1', 'STREET', schema='sap')
    op.drop_column('lfa1', 'HOUSE_NUM1', schema='sap')
    op.drop_column('lfa1', 'BRSCH', schema='sap')
    op.drop_column('lfa1', 'SMTP_ADDR', schema='sap')
    op.alter_column('lfb1', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Vendor Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('lfb1', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Company Code',
               existing_nullable=False,
               schema='sap')
    op.alter_column('lfb1', 'ERDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date on which record was created',
               existing_nullable=True,
               schema='sap')
    op.drop_column('lfb1', 'KVERM', schema='sap')
    op.drop_column('lfb1', 'ZGRUP', schema='sap')
    op.drop_column('lfb1', 'LNRZB', schema='sap')
    op.drop_column('lfb1', 'ZINRT', schema='sap')
    op.drop_column('lfb1', 'PERNR', schema='sap')
    op.drop_column('lfb1', 'ZUAWA', schema='sap')
    op.drop_column('lfb1', 'created_at', schema='sap')
    op.drop_column('lfb1', 'ZWELS', schema='sap')
    op.drop_column('lfb1', 'SPERR', schema='sap')
    op.drop_column('lfb1', 'ZTERM', schema='sap')
    op.drop_column('lfb1', 'AKONT', schema='sap')
    op.drop_column('lfb1', 'PAY_TYPE', schema='sap')
    op.drop_column('lfb1', 'BUSAB', schema='sap')
    op.drop_column('lfb1', 'EIKTO', schema='sap')
    op.drop_column('lfb1', 'ERNAM', schema='sap')
    op.drop_column('lfb1', 'LNRZE', schema='sap')
    op.drop_column('lfb1', 'ZHBKLS', schema='sap')
    op.drop_column('lfb1', 'XVERR', schema='sap')
    op.drop_column('lfb1', 'FDGRV', schema='sap')
    op.drop_column('lfb1', 'ZSABE', schema='sap')
    op.drop_column('lfb1', 'VZSKZ', schema='sap')
    op.drop_column('lfb1', 'ZINDT', schema='sap')
    op.drop_column('lfb1', 'LOEVM', schema='sap')
    op.drop_column('lfb1', 'ZAMNR', schema='sap')
    op.drop_column('lfb1', 'BEGRU', schema='sap')
    op.alter_column('mkpf', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Number of Material Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mkpf', 'MJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Material Document Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mkpf', 'BLDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'USNAM',
               existing_type=sa.VARCHAR(length=12),
               comment=None,
               existing_comment='User Name',
               existing_nullable=True,
               schema='sap')
    op.drop_column('mkpf', 'VGART', schema='sap')
    op.drop_column('mkpf', 'TCODE', schema='sap')
    op.drop_column('mkpf', 'BKTXT', schema='sap')
    op.drop_column('mkpf', 'CPUDT', schema='sap')
    op.drop_column('mkpf', 'BLART', schema='sap')
    op.drop_column('mkpf', 'created_at', schema='sap')
    op.drop_column('mkpf', 'AEDAT', schema='sap')
    op.drop_column('mkpf', 'CPUTM', schema='sap')
    op.drop_column('mkpf', 'XBLNR', schema='sap')
    op.alter_column('mseg', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Number of Material Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'MJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Material Document Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'ZEILE',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Item in Material Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'BWART',
               existing_type=sa.VARCHAR(length=3),
               comment=None,
               existing_comment='Movement Type (Inventory Management)',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'MATNR',
               existing_type=sa.VARCHAR(length=18),
               comment=None,
               existing_comment='Material Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'MENGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Quantity',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Vendor number',
               existing_nullable=True,
               schema='sap')
    op.drop_column('mseg', 'LGORT', schema='sap')
    op.drop_column('mseg', 'EBELP', schema='sap')
    op.drop_column('mseg', 'KUNNR', schema='sap')
    op.drop_column('mseg', 'SMBLN', schema='sap')
    op.drop_column('mseg', 'LFBJA', schema='sap')
    op.drop_column('mseg', 'MEINS', schema='sap')
    op.drop_column('mseg', 'KOSTL', schema='sap')
    op.drop_column('mseg', 'SJAHR', schema='sap')
    op.drop_column('mseg', 'INSMK', schema='sap')
    op.drop_column('mseg', 'LFPOS', schema='sap')
    op.drop_column('mseg', 'ANLN2', schema='sap')
    op.drop_column('mseg', 'KOKRS', schema='sap')
    op.drop_column('mseg', 'WERKS', schema='sap')
    op.drop_column('mseg', 'ZUGIU', schema='sap')
    op.drop_column('mseg', 'AUFNR', schema='sap')
    op.drop_column('mseg', 'LFBNR', schema='sap')
    op.drop_column('mseg', 'created_at', schema='sap')
    op.drop_column('mseg', 'ERFME', schema='sap')
    op.drop_column('mseg', 'SOBKZ', schema='sap')
    op.drop_column('mseg', 'CHARG', schema='sap')
    op.drop_column('mseg', 'EBELN', schema='sap')
    op.drop_column('mseg', 'PROJK', schema='sap')
    op.drop_column('mseg', 'ANLN1', schema='sap')
    op.drop_column('mseg', 'SMBLP', schema='sap')
    op.drop_column('mseg', 'ERFMG', schema='sap')
    op.alter_column('rbkp', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Document Number of an Invoice Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rbkp', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rbkp', 'BLDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BUDAT',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Tax Number 1',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Company Code',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'RMWWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Gross Invoice Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.drop_column('rbkp', 'ZFBDT', schema='sap')
    op.drop_column('rbkp', 'ZBD1T', schema='sap')
    op.drop_column('rbkp', 'LANDL', schema='sap')
    op.drop_column('rbkp', 'ZBD2P', schema='sap')
    op.drop_column('rbkp', 'USNAM', schema='sap')
    op.drop_column('rbkp', 'WWERT', schema='sap')
    op.drop_column('rbkp', 'DIEKZ', schema='sap')
    op.drop_column('rbkp', 'ZBD2T', schema='sap')
    op.drop_column('rbkp', 'TCODE', schema='sap')
    op.drop_column('rbkp', 'STCEG', schema='sap')
    op.drop_column('rbkp', 'LZBKZ', schema='sap')
    op.drop_column('rbkp', 'KURSF', schema='sap')
    op.drop_column('rbkp', 'BEZNK', schema='sap')
    op.drop_column('rbkp', 'created_at', schema='sap')
    op.drop_column('rbkp', 'ZBD3T', schema='sap')
    op.drop_column('rbkp', 'XBLNR', schema='sap')
    op.drop_column('rbkp', 'MWSKZ', schema='sap')
    op.drop_column('rbkp', 'ZTERM', schema='sap')
    op.drop_column('rbkp', 'CPUDT', schema='sap')
    op.drop_column('rbkp', 'BLART', schema='sap')
    op.drop_column('rbkp', 'WAERS', schema='sap')
    op.drop_column('rbkp', 'ZBD1P', schema='sap')
    op.drop_column('rbkp', 'WMWST', schema='sap')
    op.drop_column('rbkp', 'CPUTM', schema='sap')
    op.alter_column('rseg', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Document Number of an Invoice Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'BUZEI',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment='Item List Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Purchasing Document Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Item Number of Purchasing Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'WRBTR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'MENGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Quantity',
               existing_nullable=True,
               schema='sap')
    op.drop_column('rseg', 'BWKEY', schema='sap')
    op.drop_column('rseg', 'BUKRS', schema='sap')
    op.drop_column('rseg', 'BWTAR', schema='sap')
    op.drop_column('rseg', 'SALK3', schema='sap')
    op.drop_column('rseg', 'BPMNG', schema='sap')
    op.drop_column('rseg', 'STPRS', schema='sap')
    op.drop_column('rseg', 'ZEKKN', schema='sap')
    op.drop_column('rseg', 'VPRSV', schema='sap')
    op.drop_column('rseg', 'SKFBP', schema='sap')
    op.drop_column('rseg', 'VERPR', schema='sap')
    op.drop_column('rseg', 'BPRME', schema='sap')
    op.drop_column('rseg', 'WERKS', schema='sap')
    op.drop_column('rseg', 'PEINH', schema='sap')
    op.drop_column('rseg', 'created_at', schema='sap')
    op.drop_column('rseg', 'KSCHL', schema='sap')
    op.drop_column('rseg', 'MWSKZ', schema='sap')
    op.drop_column('rseg', 'SHKZG', schema='sap')
    op.drop_column('rseg', 'TXJCD', schema='sap')
    op.drop_column('rseg', 'BSTME', schema='sap')
    op.drop_column('rseg', 'LBKUM', schema='sap')
    op.drop_column('rseg', 'MATNR', schema='sap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rseg', sa.Column('MATNR', sa.VARCHAR(length=18), autoincrement=False, nullable=True, comment='Material Number'), schema='sap')
    op.add_column('rseg', sa.Column('LBKUM', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Total Valuated Stock'), schema='sap')
    op.add_column('rseg', sa.Column('BSTME', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Purchase order unit of measure'), schema='sap')
    op.add_column('rseg', sa.Column('TXJCD', sa.VARCHAR(length=15), autoincrement=False, nullable=True, comment='Tax Jur.'), schema='sap')
    op.add_column('rseg', sa.Column('SHKZG', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Debit/Credit Indicator'), schema='sap')
    op.add_column('rseg', sa.Column('MWSKZ', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Tax on sales/purchases code'), schema='sap')
    op.add_column('rseg', sa.Column('KSCHL', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Condition Type'), schema='sap')
    op.add_column('rseg', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('rseg', sa.Column('PEINH', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Price Unit'), schema='sap')
    op.add_column('rseg', sa.Column('WERKS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Plant'), schema='sap')
    op.add_column('rseg', sa.Column('BPRME', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Order Price Unit (Purchasing)'), schema='sap')
    op.add_column('rseg', sa.Column('VERPR', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Moving Average Price/Periodic Unit Price'), schema='sap')
    op.add_column('rseg', sa.Column('SKFBP', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Amount eligible for cash discount'), schema='sap')
    op.add_column('rseg', sa.Column('VPRSV', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Price control indicator'), schema='sap')
    op.add_column('rseg', sa.Column('ZEKKN', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Sequential number of account assignment'), schema='sap')
    op.add_column('rseg', sa.Column('STPRS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Standard price'), schema='sap')
    op.add_column('rseg', sa.Column('BPMNG', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Quantity in Purchase Order Price Unit'), schema='sap')
    op.add_column('rseg', sa.Column('SALK3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Value of Total Valuated Stock'), schema='sap')
    op.add_column('rseg', sa.Column('BWTAR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Valuation Type'), schema='sap')
    op.add_column('rseg', sa.Column('BUKRS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Company Code'), schema='sap')
    op.add_column('rseg', sa.Column('BWKEY', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Valuation Area'), schema='sap')
    op.alter_column('rseg', 'MENGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Quantity',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'WRBTR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment='Item Number of Purchasing Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchasing Document Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'BUZEI',
               existing_type=sa.VARCHAR(length=6),
               comment='Item List Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Document Number of an Invoice Document',
               existing_nullable=False,
               schema='sap')
    op.add_column('rbkp', sa.Column('CPUTM', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Time of Entry'), schema='sap')
    op.add_column('rbkp', sa.Column('WMWST', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Tax amount in document currency'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD1P', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount percentage 1'), schema='sap')
    op.add_column('rbkp', sa.Column('WAERS', sa.VARCHAR(length=5), autoincrement=False, nullable=True, comment='Currency Key'), schema='sap')
    op.add_column('rbkp', sa.Column('BLART', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Document Type'), schema='sap')
    op.add_column('rbkp', sa.Column('CPUDT', sa.DATE(), autoincrement=False, nullable=True, comment='Day On Which Accounting Document Was Entered'), schema='sap')
    op.add_column('rbkp', sa.Column('ZTERM', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Terms of Payment Key'), schema='sap')
    op.add_column('rbkp', sa.Column('MWSKZ', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Tax code'), schema='sap')
    op.add_column('rbkp', sa.Column('XBLNR', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Reference Document Number'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD3T', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount days 3'), schema='sap')
    op.add_column('rbkp', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('rbkp', sa.Column('BEZNK', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Unplanned delivery costs'), schema='sap')
    op.add_column('rbkp', sa.Column('KURSF', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exchange Rate'), schema='sap')
    op.add_column('rbkp', sa.Column('LZBKZ', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='State central bank indicator'), schema='sap')
    op.add_column('rbkp', sa.Column('STCEG', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='VAT Registration Number'), schema='sap')
    op.add_column('rbkp', sa.Column('TCODE', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Transaction Code'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD2T', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount days 2'), schema='sap')
    op.add_column('rbkp', sa.Column('DIEKZ', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Service indicator'), schema='sap')
    op.add_column('rbkp', sa.Column('WWERT', sa.DATE(), autoincrement=False, nullable=True, comment='Translation date'), schema='sap')
    op.add_column('rbkp', sa.Column('USNAM', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='User Name'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD2P', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount percentage 2'), schema='sap')
    op.add_column('rbkp', sa.Column('LANDL', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Country of supplying country'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD1T', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount days 1'), schema='sap')
    op.add_column('rbkp', sa.Column('ZFBDT', sa.DATE(), autoincrement=False, nullable=True, comment='Baseline Date for Due Date Calculation'), schema='sap')
    op.alter_column('rbkp', 'RMWWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Gross Invoice Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment='Company Code',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Tax Number 1',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rbkp', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Document Number of an Invoice Document',
               existing_nullable=False,
               schema='sap')
    op.add_column('mseg', sa.Column('ERFMG', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Quantity in unit of entry'), schema='sap')
    op.add_column('mseg', sa.Column('SMBLP', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Item in material document'), schema='sap')
    op.add_column('mseg', sa.Column('ANLN1', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Main Asset Number'), schema='sap')
    op.add_column('mseg', sa.Column('PROJK', sa.VARCHAR(length=8), autoincrement=False, nullable=True, comment='WBS Element'), schema='sap')
    op.add_column('mseg', sa.Column('EBELN', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Purchase Order Number'), schema='sap')
    op.add_column('mseg', sa.Column('CHARG', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Batch Number'), schema='sap')
    op.add_column('mseg', sa.Column('SOBKZ', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Special Stock Indicator'), schema='sap')
    op.add_column('mseg', sa.Column('ERFME', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Unit of entry'), schema='sap')
    op.add_column('mseg', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('mseg', sa.Column('LFBNR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Document number of a reference document'), schema='sap')
    op.add_column('mseg', sa.Column('AUFNR', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Order Number'), schema='sap')
    op.add_column('mseg', sa.Column('ZUGIU', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Posting to Stock in Quality Inspection'), schema='sap')
    op.add_column('mseg', sa.Column('WERKS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Plant'), schema='sap')
    op.add_column('mseg', sa.Column('KOKRS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Controlling Area'), schema='sap')
    op.add_column('mseg', sa.Column('ANLN2', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Asset Subnumber'), schema='sap')
    op.add_column('mseg', sa.Column('LFPOS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Item of a reference document'), schema='sap')
    op.add_column('mseg', sa.Column('INSMK', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Stock Type'), schema='sap')
    op.add_column('mseg', sa.Column('SJAHR', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Material document year'), schema='sap')
    op.add_column('mseg', sa.Column('KOSTL', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Cost Center'), schema='sap')
    op.add_column('mseg', sa.Column('MEINS', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Unit of Measure'), schema='sap')
    op.add_column('mseg', sa.Column('LFBJA', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Fiscal year of a reference document'), schema='sap')
    op.add_column('mseg', sa.Column('SMBLN', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Number of material document'), schema='sap')
    op.add_column('mseg', sa.Column('KUNNR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Account number of customer'), schema='sap')
    op.add_column('mseg', sa.Column('EBELP', sa.VARCHAR(length=5), autoincrement=False, nullable=True, comment='PO Item Number'), schema='sap')
    op.add_column('mseg', sa.Column('LGORT', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Storage Location'), schema='sap')
    op.alter_column('mseg', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Vendor number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'MENGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Quantity',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'MATNR',
               existing_type=sa.VARCHAR(length=18),
               comment='Material Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'BWART',
               existing_type=sa.VARCHAR(length=3),
               comment='Movement Type (Inventory Management)',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mseg', 'ZEILE',
               existing_type=sa.VARCHAR(length=4),
               comment='Item in Material Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'MJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment='Material Document Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Number of Material Document',
               existing_nullable=False,
               schema='sap')
    op.add_column('mkpf', sa.Column('XBLNR', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Reference Document Number'), schema='sap')
    op.add_column('mkpf', sa.Column('CPUTM', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Time of Entry'), schema='sap')
    op.add_column('mkpf', sa.Column('AEDAT', sa.DATE(), autoincrement=False, nullable=True, comment='Date of the Last Document Change'), schema='sap')
    op.add_column('mkpf', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('mkpf', sa.Column('BLART', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Document Type'), schema='sap')
    op.add_column('mkpf', sa.Column('CPUDT', sa.DATE(), autoincrement=False, nullable=True, comment='Day On Which Accounting Document Was Entered'), schema='sap')
    op.add_column('mkpf', sa.Column('BKTXT', sa.VARCHAR(length=25), autoincrement=False, nullable=True, comment='Document Header Text'), schema='sap')
    op.add_column('mkpf', sa.Column('TCODE', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Transaction Code'), schema='sap')
    op.add_column('mkpf', sa.Column('VGART', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Transaction/Event Type'), schema='sap')
    op.alter_column('mkpf', 'USNAM',
               existing_type=sa.VARCHAR(length=12),
               comment='User Name',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'MJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment='Material Document Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mkpf', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Number of Material Document',
               existing_nullable=False,
               schema='sap')
    op.add_column('lfb1', sa.Column('BEGRU', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Authorization Group'), schema='sap')
    op.add_column('lfb1', sa.Column('ZAMNR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Ad-hoc agent'), schema='sap')
    op.add_column('lfb1', sa.Column('LOEVM', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Deletion Flag for Company Code'), schema='sap')
    op.add_column('lfb1', sa.Column('ZINDT', sa.DATE(), autoincrement=False, nullable=True, comment='Date of last interest calculation'), schema='sap')
    op.add_column('lfb1', sa.Column('VZSKZ', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Interest calculation indicator'), schema='sap')
    op.add_column('lfb1', sa.Column('ZSABE', sa.VARCHAR(length=15), autoincrement=False, nullable=True, comment='Clerk at vendor'), schema='sap')
    op.add_column('lfb1', sa.Column('FDGRV', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Planning group'), schema='sap')
    op.add_column('lfb1', sa.Column('XVERR', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Clearing with customer'), schema='sap')
    op.add_column('lfb1', sa.Column('ZHBKLS', sa.VARCHAR(length=5), autoincrement=False, nullable=True, comment='House Bank'), schema='sap')
    op.add_column('lfb1', sa.Column('LNRZE', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Head office account number'), schema='sap')
    op.add_column('lfb1', sa.Column('ERNAM', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Name of Person who Created the Object'), schema='sap')
    op.add_column('lfb1', sa.Column('EIKTO', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Our account number with the vendor'), schema='sap')
    op.add_column('lfb1', sa.Column('BUSAB', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Accounting clerk'), schema='sap')
    op.add_column('lfb1', sa.Column('PAY_TYPE', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Payment Type'), schema='sap')
    op.add_column('lfb1', sa.Column('AKONT', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Reconciliation Account'), schema='sap')
    op.add_column('lfb1', sa.Column('ZTERM', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Terms of Payment Key'), schema='sap')
    op.add_column('lfb1', sa.Column('SPERR', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Posting block for company code'), schema='sap')
    op.add_column('lfb1', sa.Column('ZWELS', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='List of Respected Payment Methods'), schema='sap')
    op.add_column('lfb1', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('lfb1', sa.Column('ZUAWA', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Key for sorting according to assignment numbers'), schema='sap')
    op.add_column('lfb1', sa.Column('PERNR', sa.VARCHAR(length=8), autoincrement=False, nullable=True, comment='Personnel Number'), schema='sap')
    op.add_column('lfb1', sa.Column('ZINRT', sa.INTEGER(), autoincrement=False, nullable=True, comment='Interest calculation frequency'), schema='sap')
    op.add_column('lfb1', sa.Column('LNRZB', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Alternative payee'), schema='sap')
    op.add_column('lfb1', sa.Column('ZGRUP', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Payment grouping'), schema='sap')
    op.add_column('lfb1', sa.Column('KVERM', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='Memo'), schema='sap')
    op.alter_column('lfb1', 'ERDAT',
               existing_type=sa.DATE(),
               comment='Date on which record was created',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfb1', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment='Company Code',
               existing_nullable=False,
               schema='sap')
    op.alter_column('lfb1', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Vendor Number',
               existing_nullable=False,
               schema='sap')
    op.add_column('lfa1', sa.Column('SMTP_ADDR', sa.VARCHAR(length=241), autoincrement=False, nullable=True, comment='E-Mail Address'), schema='sap')
    op.add_column('lfa1', sa.Column('BRSCH', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Industry Key'), schema='sap')
    op.add_column('lfa1', sa.Column('HOUSE_NUM1', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='House Number'), schema='sap')
    op.add_column('lfa1', sa.Column('STREET', sa.VARCHAR(length=35), autoincrement=False, nullable=True, comment='Street'), schema='sap')
    op.add_column('lfa1', sa.Column('LANGU', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Language Key'), schema='sap')
    op.add_column('lfa1', sa.Column('ERNAM', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Name of Person who Created the Object'), schema='sap')
    op.add_column('lfa1', sa.Column('STCD1', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Tax Number 1 (GST)'), schema='sap')
    op.add_column('lfa1', sa.Column('NAME4', sa.VARCHAR(length=35), autoincrement=False, nullable=True, comment='Name 4'), schema='sap')
    op.add_column('lfa1', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('lfa1', sa.Column('KONZS', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Group Key'), schema='sap')
    op.add_column('lfa1', sa.Column('NAME3', sa.VARCHAR(length=35), autoincrement=False, nullable=True, comment='Name 3'), schema='sap')
    op.add_column('lfa1', sa.Column('STCEG', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='VAT Registration Number'), schema='sap')
    op.add_column('lfa1', sa.Column('REGION', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Region (State)'), schema='sap')
    op.add_column('lfa1', sa.Column('SPERZ', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Payment Block'), schema='sap')
    op.add_column('lfa1', sa.Column('TELX1', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='Telex Number'), schema='sap')
    op.add_column('lfa1', sa.Column('TELF1', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='First Telephone Number'), schema='sap')
    op.add_column('lfa1', sa.Column('TELTX', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='Teletex Number'), schema='sap')
    op.add_column('lfa1', sa.Column('STCD3', sa.VARCHAR(length=18), autoincrement=False, nullable=True, comment='Tax Number 3'), schema='sap')
    op.add_column('lfa1', sa.Column('LOEVM', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Central Deletion Flag'), schema='sap')
    op.add_column('lfa1', sa.Column('POST_CODE1', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Postal Code'), schema='sap')
    op.add_column('lfa1', sa.Column('UPDAT', sa.DATE(), autoincrement=False, nullable=True, comment='Date of Last Update'), schema='sap')
    op.add_column('lfa1', sa.Column('TELFX', sa.VARCHAR(length=31), autoincrement=False, nullable=True, comment='Fax Number'), schema='sap')
    op.add_column('lfa1', sa.Column('SPERR', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Central Posting Block'), schema='sap')
    op.add_column('lfa1', sa.Column('STCD2', sa.VARCHAR(length=11), autoincrement=False, nullable=True, comment='Tax Number 2'), schema='sap')
    op.add_column('lfa1', sa.Column('TELF2', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Second Telephone Number'), schema='sap')
    op.add_column('lfa1', sa.Column('FISKN', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Account number of the master record'), schema='sap')
    op.add_column('lfa1', sa.Column('MBRSH', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Industry Sector'), schema='sap')
    op.add_column('lfa1', sa.Column('UPTIM', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Time of last update'), schema='sap')
    op.add_column('lfa1', sa.Column('VBUND', sa.VARCHAR(length=6), autoincrement=False, nullable=True, comment='Trading Partner'), schema='sap')
    op.add_column('lfa1', sa.Column('CITY1', sa.VARCHAR(length=35), autoincrement=False, nullable=True, comment='City'), schema='sap')
    op.add_column('lfa1', sa.Column('NAME2', sa.VARCHAR(length=35), autoincrement=False, nullable=True, comment='Name 2'), schema='sap')
    op.add_column('lfa1', sa.Column('KTOKK', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Vendor Account Group'), schema='sap')
    op.alter_column('lfa1', 'ERDAT',
               existing_type=sa.DATE(),
               comment='Date on which record was created',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'COUNTRY',
               existing_type=sa.VARCHAR(length=3),
               comment='Country Key',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'NAME1',
               existing_type=sa.VARCHAR(length=35),
               comment='Name 1',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Vendor Number',
               existing_nullable=False,
               schema='sap')
    op.add_column('ekpo', sa.Column('AGDAT', sa.DATE(), autoincrement=False, nullable=True, comment='Deadline for Submission of Quotation'), schema='sap')
    op.add_column('ekpo', sa.Column('BEDNR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Requirement Tracking Number'), schema='sap')
    op.add_column('ekpo', sa.Column('BONUS', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Settlement Group'), schema='sap')
    op.add_column('ekpo', sa.Column('BPUMZ', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Numerator for Conversion of Order Unit to Base Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('MWSKZ', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Tax on sales/purchases code'), schema='sap')
    op.add_column('ekpo', sa.Column('BRTWR', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Gross order value'), schema='sap')
    op.add_column('ekpo', sa.Column('AEDAT', sa.DATE(), autoincrement=False, nullable=True, comment='Purchasing document item change date'), schema='sap')
    op.add_column('ekpo', sa.Column('BWTTY', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Valuation Category'), schema='sap')
    op.add_column('ekpo', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('ekpo', sa.Column('PRSDR', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Print Price'), schema='sap')
    op.add_column('ekpo', sa.Column('PEINH', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Price Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('STATU', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='RFQ status'), schema='sap')
    op.add_column('ekpo', sa.Column('WERKS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Plant'), schema='sap')
    op.add_column('ekpo', sa.Column('SPINF', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Indicator: Update Info Record'), schema='sap')
    op.add_column('ekpo', sa.Column('INSMK', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Stock Type'), schema='sap')
    op.add_column('ekpo', sa.Column('ABSKZ', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Rejection Indicator'), schema='sap')
    op.add_column('ekpo', sa.Column('WEBAZ', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Goods receipt processing time'), schema='sap')
    op.add_column('ekpo', sa.Column('MATKL', sa.VARCHAR(length=9), autoincrement=False, nullable=True, comment='Material Group'), schema='sap')
    op.add_column('ekpo', sa.Column('EMATN', sa.VARCHAR(length=18), autoincrement=False, nullable=True, comment='Material number'), schema='sap')
    op.add_column('ekpo', sa.Column('BWTAR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Valuation Type'), schema='sap')
    op.add_column('ekpo', sa.Column('BUKRS', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Company Code'), schema='sap')
    op.add_column('ekpo', sa.Column('TXZ01', sa.VARCHAR(length=40), autoincrement=False, nullable=True, comment='Short Text'), schema='sap')
    op.add_column('ekpo', sa.Column('MEINS', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Order Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('LOEKZ', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Deletion indicator'), schema='sap')
    op.add_column('ekpo', sa.Column('BPUMN', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Denominator for Conv. of Order Unit to Base Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('LGORT', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Storage Location'), schema='sap')
    op.alter_column('ekpo', 'NETWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Order Value in PO Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'NETPR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Price in Purchasing Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'MENGE',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Purchase Order Quantity',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'MATNR',
               existing_type=sa.VARCHAR(length=18),
               comment='Material Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment='Item Number of Purchasing Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekpo', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchasing Document Number',
               existing_nullable=False,
               schema='sap')
    op.add_column('ekko', sa.Column('ZBD1P', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount percentage 1'), schema='sap')
    op.add_column('ekko', sa.Column('ERNAM', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Name of Person who Created the Object'), schema='sap')
    op.add_column('ekko', sa.Column('BSTYP', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Purchasing Document Category'), schema='sap')
    op.add_column('ekko', sa.Column('ZTERM', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Terms of Payment Key'), schema='sap')
    op.add_column('ekko', sa.Column('PROCSTAT', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Processing State'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD3T', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount days 3'), schema='sap')
    op.add_column('ekko', sa.Column('LIBRE', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Release group'), schema='sap')
    op.add_column('ekko', sa.Column('WKURS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exchange Rate'), schema='sap')
    op.add_column('ekko', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('ekko', sa.Column('EKGRP', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Purchasing Group'), schema='sap')
    op.add_column('ekko', sa.Column('KDATE', sa.DATE(), autoincrement=False, nullable=True, comment='End of Validity Period'), schema='sap')
    op.add_column('ekko', sa.Column('STATU', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Status of Purchasing Document'), schema='sap')
    op.add_column('ekko', sa.Column('LPNOH', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Last item number'), schema='sap')
    op.add_column('ekko', sa.Column('RESWK', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Supplying (issuing) plant'), schema='sap')
    op.add_column('ekko', sa.Column('BSAKU', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Control indicator'), schema='sap')
    op.add_column('ekko', sa.Column('BWVKO', sa.DATE(), autoincrement=False, nullable=True, comment='Date of last document update'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD2T', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount days 2'), schema='sap')
    op.add_column('ekko', sa.Column('KNUMV', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Number of the document condition'), schema='sap')
    op.add_column('ekko', sa.Column('KDATB', sa.DATE(), autoincrement=False, nullable=True, comment='Start of Validity Period'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD2P', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount percentage 2'), schema='sap')
    op.add_column('ekko', sa.Column('EKORG', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Purchasing Organization'), schema='sap')
    op.add_column('ekko', sa.Column('KUFIX', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Indicator: Fix exchange rate'), schema='sap')
    op.add_column('ekko', sa.Column('BEDAT', sa.DATE(), autoincrement=False, nullable=True, comment='Purchasing Document Date'), schema='sap')
    op.add_column('ekko', sa.Column('BSART', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Purchasing Document Type'), schema='sap')
    op.add_column('ekko', sa.Column('LOEKZ', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Deletion indicator'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD1T', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Cash discount days 1'), schema='sap')
    op.alter_column('ekko', 'NETWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Order Value',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'WAERS',
               existing_type=sa.VARCHAR(length=5),
               comment='Currency Key',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Vendor Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'AEDAT',
               existing_type=sa.DATE(),
               comment='Date on Which Record Was Created',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment='Company Code',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchasing Document Number',
               existing_nullable=False,
               schema='sap')
    op.add_column('bseg', sa.Column('WMWST', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Tax amount in document currency'), schema='sap')
    op.add_column('bseg', sa.Column('FWZUZ', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Provision amount in document currency'), schema='sap')
    op.add_column('bseg', sa.Column('GSBER', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Business Area'), schema='sap')
    op.add_column('bseg', sa.Column('HWBAS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Tax base amount in local currency'), schema='sap')
    op.add_column('bseg', sa.Column('PROJK', sa.VARCHAR(length=8), autoincrement=False, nullable=True, comment='WBS Element'), schema='sap')
    op.add_column('bseg', sa.Column('BSCHL', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Posting Key'), schema='sap')
    op.add_column('bseg', sa.Column('SHKZG', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Debit/Credit Indicator'), schema='sap')
    op.add_column('bseg', sa.Column('MWSKZ', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Tax on sales/purchases code'), schema='sap')
    op.add_column('bseg', sa.Column('HKONT', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='General Ledger Account'), schema='sap')
    op.add_column('bseg', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('bseg', sa.Column('AUFNR', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='Order Number'), schema='sap')
    op.add_column('bseg', sa.Column('PARGB', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment="Trading partner's business area"), schema='sap')
    op.add_column('bseg', sa.Column('KOART', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Account Type'), schema='sap')
    op.add_column('bseg', sa.Column('FWBAS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Tax base amount in document currency'), schema='sap')
    op.add_column('bseg', sa.Column('HWZUZ', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Provision amount in local currency'), schema='sap')
    op.add_column('bseg', sa.Column('KOSTL', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Cost Center'), schema='sap')
    op.add_column('bseg', sa.Column('BZIRK', sa.VARCHAR(length=6), autoincrement=False, nullable=True, comment='Sales District'), schema='sap')
    op.add_column('bseg', sa.Column('KUNNR', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Customer Number'), schema='sap')
    op.add_column('bseg', sa.Column('MWSTS', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Tax amount in local currency'), schema='sap')
    op.add_column('bseg', sa.Column('UMSKZ', sa.VARCHAR(length=1), autoincrement=False, nullable=True, comment='Special G/L Indicator'), schema='sap')
    op.alter_column('bseg', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Account Number of Vendor or Creditor',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bseg', 'WRBTR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bseg', 'DMBTR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Amount in Local Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bseg', 'BUZEI',
               existing_type=sa.VARCHAR(length=3),
               comment='Line Item Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Accounting Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bseg', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment='Company Code',
               existing_nullable=False,
               schema='sap')
    op.add_column('bkpf', sa.Column('XBLNR', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Reference Document Number'), schema='sap')
    op.add_column('bkpf', sa.Column('CPUTM', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Time of Entry'), schema='sap')
    op.add_column('bkpf', sa.Column('STBLG', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Reverse Document Number'), schema='sap')
    op.add_column('bkpf', sa.Column('UPDDT', sa.DATE(), autoincrement=False, nullable=True, comment='Date of the Last Update'), schema='sap')
    op.add_column('bkpf', sa.Column('AEDAT', sa.DATE(), autoincrement=False, nullable=True, comment='Date of the Last Document Change'), schema='sap')
    op.add_column('bkpf', sa.Column('KZWRS', sa.VARCHAR(length=5), autoincrement=False, nullable=True, comment='Group Currency'), schema='sap')
    op.add_column('bkpf', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='sap')
    op.add_column('bkpf', sa.Column('BLART', sa.VARCHAR(length=2), autoincrement=False, nullable=True, comment='Document Type'), schema='sap')
    op.add_column('bkpf', sa.Column('WWERT', sa.DATE(), autoincrement=False, nullable=True, comment='Translation date'), schema='sap')
    op.add_column('bkpf', sa.Column('STJAH', sa.VARCHAR(length=4), autoincrement=False, nullable=True, comment='Reverse document fiscal year'), schema='sap')
    op.add_column('bkpf', sa.Column('KURSF', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Exchange Rate'), schema='sap')
    op.add_column('bkpf', sa.Column('DBBLG', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='Recurring entry document number'), schema='sap')
    op.add_column('bkpf', sa.Column('CPUDT', sa.DATE(), autoincrement=False, nullable=True, comment='Day On Which Accounting Document Was Entered'), schema='sap')
    op.add_column('bkpf', sa.Column('BKTXT', sa.VARCHAR(length=25), autoincrement=False, nullable=True, comment='Document Header Text'), schema='sap')
    op.add_column('bkpf', sa.Column('MONAT', sa.INTEGER(), autoincrement=False, nullable=True, comment='Fiscal Period'), schema='sap')
    op.add_column('bkpf', sa.Column('BVORG', sa.VARCHAR(length=16), autoincrement=False, nullable=True, comment='Number of a Cross-Company Code Transaction'), schema='sap')
    op.add_column('bkpf', sa.Column('USNAM', sa.VARCHAR(length=12), autoincrement=False, nullable=True, comment='User Name'), schema='sap')
    op.add_column('bkpf', sa.Column('TCODE', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Transaction Code'), schema='sap')
    op.alter_column('bkpf', 'WAERS',
               existing_type=sa.VARCHAR(length=5),
               comment='Currency Key',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'GJAHR',
               existing_type=sa.VARCHAR(length=4),
               comment='Fiscal Year',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bkpf', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Accounting Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('bkpf', 'BUKRS',
               existing_type=sa.VARCHAR(length=4),
               comment='Company Code',
               existing_nullable=False,
               schema='sap')
    op.create_table('promoted_invoices',
    sa.Column('invoice_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('invoice_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('posting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('_created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('invoice_number', 'fiscal_year', name='promoted_invoices_pkey'),
    schema='ai'
    )
    op.create_index('idx_promoted_invoices_updated_at', 'promoted_invoices', ['_updated_at'], unique=False, schema='ai')
    op.create_table('ai_vendors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ai.ai_vendors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('LIFNR', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='SAP Vendor Number Reference'),
    sa.Column('NAME1', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('AI_Score', sa.INTEGER(), autoincrement=False, nullable=True, comment='AI Generated Risk/Quality Score'),
    sa.Column('AI_Classification', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_vendors_pkey'),
    sa.UniqueConstraint('LIFNR', name='ai_vendors_LIFNR_key'),
    schema='ai'
    )
    op.create_table('_sync_state',
    sa.Column('entity_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_watermark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('records_synced', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_status', sa.VARCHAR(length=20), server_default=sa.text("'PENDING'::character varying"), autoincrement=False, nullable=True),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_syncs', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('entity_name', name='_sync_state_pkey'),
    schema='ai'
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ai.users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    schema='ai'
    )
    op.create_index('ix_ai_users_id', 'users', ['id'], unique=False, schema='ai')
    op.create_table('promoted_inventory',
    sa.Column('doc_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('doc_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('material_number', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('plant', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('storage_location', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('unit', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('_created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('doc_number', 'doc_year', 'item_number', name='promoted_inventory_pkey'),
    schema='ai'
    )
    op.create_index('idx_promoted_inventory_updated_at', 'promoted_inventory', ['_updated_at'], unique=False, schema='ai')
    op.create_table('ai_invoices',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ai.ai_invoices_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('BELNR', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='SAP Document Number Reference'),
    sa.Column('GJAHR', sa.VARCHAR(length=4), autoincrement=False, nullable=False, comment='SAP Fiscal Year Reference'),
    sa.Column('LIFNR', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('TotalAmount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Anomalous', sa.INTEGER(), autoincrement=False, nullable=True, comment='1 if AI detects anomaly'),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ai_invoices_pkey'),
    schema='ai'
    )
    op.create_table('synthetic_data',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ai.synthetic_data_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('synthetic_value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='synthetic_data_pkey'),
    sa.UniqueConstraint('email', name='synthetic_data_email_key'),
    schema='ai'
    )
    op.create_index('ix_ai_synthetic_data_id', 'synthetic_data', ['id'], unique=False, schema='ai')
    op.create_table('promoted_vendors',
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sap_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('business_sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_on', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('_created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('vendor_id', name='promoted_vendors_pkey'),
    schema='ai'
    )
    op.create_index('idx_promoted_vendors_updated_at', 'promoted_vendors', ['_updated_at'], unique=False, schema='ai')
    op.create_table('promoted_purchase_orders',
    sa.Column('po_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('item_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vendor_code', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('material_number', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=True),
    sa.Column('net_price', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('po_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('_created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('_updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('po_number', 'item_number', name='promoted_purchase_orders_pkey'),
    schema='ai'
    )
    op.create_index('idx_promoted_purchase_orders_updated_at', 'promoted_purchase_orders', ['_updated_at'], unique=False, schema='ai')
    # ### end Alembic commands ###
