"""add_sap_fk_constraints

Revision ID: cc97781dc9cf
Revises: 9a3d5175725f
Create Date: 2026-02-18 16:37:22.676120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc97781dc9cf'
down_revision: Union[str, None] = '9a3d5175725f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bkpf_bukrs_belnr_gjahr_key', 'bkpf', ['BUKRS', 'BELNR', 'GJAHR'], schema='sap_layer')
    op.create_unique_constraint('bseg_keys_unique', 'bseg', ['BUKRS', 'BELNR', 'GJAHR', 'BUZEI'], schema='sap_layer')
    op.create_foreign_key(None, 'ekko', 'lfa1', ['LIFNR'], ['LIFNR'], source_schema='sap_layer', referent_schema='sap_layer')
    op.create_unique_constraint('ekpo_ebeln_ebelp_key', 'ekpo', ['EBELN', 'EBELP'], schema='sap_layer')
    op.create_foreign_key(None, 'ekpo', 'ekko', ['EBELN'], ['EBELN'], source_schema='sap_layer', referent_schema='sap_layer')
    op.create_unique_constraint('lfb1_lifnr_bukrs_key', 'lfb1', ['LIFNR', 'BUKRS'], schema='sap_layer')
    op.create_foreign_key(None, 'lfb1', 'lfa1', ['LIFNR'], ['LIFNR'], source_schema='sap_layer', referent_schema='sap_layer')
    op.create_unique_constraint('mkpf_mblnr_mjahr_key', 'mkpf', ['MBLNR', 'MJAHR'], schema='sap_layer')
    op.create_unique_constraint('mseg_mblnr_mjahr_zeile_key', 'mseg', ['MBLNR', 'MJAHR', 'ZEILE'], schema='sap_layer')
    op.create_unique_constraint('rbkp_belnr_gjahr_key', 'rbkp', ['BELNR', 'GJAHR'], schema='sap_layer')
    op.create_foreign_key(None, 'rbkp', 'lfa1', ['LIFNR'], ['LIFNR'], source_schema='sap_layer', referent_schema='sap_layer')
    op.create_unique_constraint('rseg_belnr_gjahr_buzei_key', 'rseg', ['BELNR', 'GJAHR', 'BUZEI'], schema='sap_layer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rseg_belnr_gjahr_buzei_key', 'rseg', schema='sap_layer', type_='unique')
    op.drop_constraint(None, 'rbkp', schema='sap_layer', type_='foreignkey')
    op.drop_constraint('rbkp_belnr_gjahr_key', 'rbkp', schema='sap_layer', type_='unique')
    op.drop_constraint('mseg_mblnr_mjahr_zeile_key', 'mseg', schema='sap_layer', type_='unique')
    op.drop_constraint('mkpf_mblnr_mjahr_key', 'mkpf', schema='sap_layer', type_='unique')
    op.drop_constraint(None, 'lfb1', schema='sap_layer', type_='foreignkey')
    op.drop_constraint('lfb1_lifnr_bukrs_key', 'lfb1', schema='sap_layer', type_='unique')
    op.drop_constraint(None, 'ekpo', schema='sap_layer', type_='foreignkey')
    op.drop_constraint('ekpo_ebeln_ebelp_key', 'ekpo', schema='sap_layer', type_='unique')
    op.drop_constraint(None, 'ekko', schema='sap_layer', type_='foreignkey')
    op.drop_constraint('bseg_keys_unique', 'bseg', schema='sap_layer', type_='unique')
    op.drop_constraint('bkpf_bukrs_belnr_gjahr_key', 'bkpf', schema='sap_layer', type_='unique')
    # ### end Alembic commands ###
