"""add_user_and_ai_sync_tables

Revision ID: faeded992b93
Revises: 13d0c07684d7
Create Date: 2026-02-21 18:59:17.212170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faeded992b93'
down_revision: Union[str, None] = '13d0c07684d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='SAP Document Number Reference'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='SAP Fiscal Year Reference'),
    sa.Column('LIFNR', sa.String(length=10), nullable=True),
    sa.Column('TotalAmount', sa.Integer(), nullable=True),
    sa.Column('Anomalous', sa.Integer(), nullable=True, comment='1 if AI detects anomaly'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ai'
    )
    op.create_table('ai_vendors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LIFNR', sa.String(length=10), nullable=False, comment='SAP Vendor Number Reference'),
    sa.Column('NAME1', sa.String(length=35), nullable=True),
    sa.Column('AI_Score', sa.Integer(), nullable=True, comment='AI Generated Risk/Quality Score'),
    sa.Column('AI_Classification', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('LIFNR'),
    schema='ai'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_users_id'), 'users', ['id'], unique=False, schema='ai')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_users_id'), table_name='users', schema='ai')
    op.drop_table('users', schema='ai')
    op.drop_table('ai_vendors', schema='ai')
    op.drop_table('ai_invoices', schema='ai')
    # ### end Alembic commands ###
