"""move_sap_to_new_schema_and_add_ai_table

Revision ID: 13d0c07684d7
Revises: cc97781dc9cf
Create Date: 2026-02-21 18:49:27.115019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d0c07684d7'
down_revision: Union[str, None] = 'cc97781dc9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('synthetic_value', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='ai'
    )
    op.create_index(op.f('ix_ai_synthetic_data_id'), 'synthetic_data', ['id'], unique=False, schema='ai')
    op.create_table('ai_action_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actionId', sa.String(), nullable=False),
    sa.Column('agentName', sa.String(), nullable=False),
    sa.Column('actionType', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=True),
    sa.Column('inputData', sa.JSON(), nullable=True),
    sa.Column('outputData', sa.JSON(), nullable=True),
    sa.Column('confidenceScore', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('executedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actionId'),
    schema='audit_layer'
    )
    op.create_table('data_access_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('accessedBy', sa.String(), nullable=False),
    sa.Column('accessedByType', sa.String(), nullable=False),
    sa.Column('accessedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='audit_layer'
    )
    op.create_table('data_change_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('oldValue', sa.JSON(), nullable=True),
    sa.Column('newValue', sa.JSON(), nullable=True),
    sa.Column('changedBy', sa.String(), nullable=False),
    sa.Column('changedByType', sa.String(), nullable=False),
    sa.Column('changedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='audit_layer'
    )
    op.create_table('curated_vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('vendorCode', sa.String(), nullable=False),
    sa.Column('vendorName', sa.String(), nullable=False),
    sa.Column('gst', sa.String(), nullable=True),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validTo', sa.DateTime(), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=True),
    sa.Column('dqScore', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('nameiy', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendorId'),
    schema='curated_layer'
    )
    op.create_table('dq_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('validity', sa.Float(), nullable=True),
    sa.Column('timeliness', sa.Float(), nullable=True),
    sa.Column('uniqueness', sa.Float(), nullable=True),
    sa.Column('compositeScore', sa.Float(), nullable=False),
    sa.Column('measuredAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dq_layer'
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('eventId', sa.String(), nullable=False),
    sa.Column('eventType', sa.String(), nullable=False),
    sa.Column('aggregateId', sa.String(), nullable=False),
    sa.Column('aggregateType', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('correlationId', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId'),
    schema='event_store'
    )
    op.create_table('extraction_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extractionId', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('extractionType', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recordsExtracted', sa.Integer(), nullable=True),
    sa.Column('recordsFailed', sa.Integer(), nullable=True),
    sa.Column('startedAt', sa.DateTime(), nullable=False),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extractionId'),
    schema='integration_layer'
    )
    op.create_table('push_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('queueId', sa.String(), nullable=False),
    sa.Column('targetSystem', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('retryCount', sa.Integer(), nullable=True),
    sa.Column('maxRetries', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('processedAt', sa.DateTime(), nullable=True),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queueId'),
    schema='push_layer'
    )
    op.create_table('bkpf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BUKRS', sa.String(length=4), nullable=False, comment='Company Code'),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Accounting Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BLART', sa.String(length=2), nullable=True, comment='Document Type'),
    sa.Column('BUDAT', sa.Date(), nullable=True, comment='Posting Date'),
    sa.Column('CPUDT', sa.Date(), nullable=True, comment='Entry Date'),
    sa.Column('USNAM', sa.String(length=12), nullable=True, comment='User Name'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('BUKRS', 'BELNR', 'GJAHR', name='bkpf_bukrs_belnr_gjahr_key'),
    schema='sap'
    )
    op.create_table('bseg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BUKRS', sa.String(length=4), nullable=False, comment='Company Code'),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Accounting Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BUZEI', sa.String(length=3), nullable=False, comment='Line Item Number'),
    sa.Column('KOART', sa.String(length=1), nullable=True, comment='Account Type'),
    sa.Column('SHKZG', sa.String(length=1), nullable=True, comment='Debit/Credit Indicator'),
    sa.Column('WRBTR', sa.Float(), nullable=True, comment='Amount in Document Currency'),
    sa.Column('DMBTR', sa.Float(), nullable=True, comment='Amount in Local Currency'),
    sa.Column('HKONT', sa.String(length=10), nullable=True, comment='General Ledger Account'),
    sa.Column('KOSTL', sa.String(length=10), nullable=True, comment='Cost Center'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('BUKRS', 'BELNR', 'GJAHR', 'BUZEI', name='bseg_keys_unique'),
    schema='sap'
    )
    op.create_table('lfa1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LIFNR', sa.String(length=10), nullable=False, comment='Vendor Number'),
    sa.Column('NAME1', sa.String(length=35), nullable=True, comment='Vendor Name'),
    sa.Column('LAND1', sa.String(length=3), nullable=True, comment='Country Key'),
    sa.Column('STCD1', sa.String(length=16), nullable=True, comment='Tax Number 1 (GST/VAT)'),
    sa.Column('KTOKK', sa.String(length=4), nullable=True, comment='Vendor Account Group'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('LIFNR'),
    schema='sap'
    )
    op.create_table('mkpf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MBLNR', sa.String(length=10), nullable=False, comment='Material Document Number'),
    sa.Column('MJAHR', sa.String(length=4), nullable=False, comment='Material Document Year'),
    sa.Column('BLDAT', sa.Date(), nullable=True, comment='Document Date'),
    sa.Column('BUDAT', sa.Date(), nullable=True, comment='Posting Date'),
    sa.Column('USNAM', sa.String(length=12), nullable=True, comment='User Name'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('MBLNR', 'MJAHR', name='mkpf_mblnr_mjahr_key'),
    schema='sap'
    )
    op.create_table('mseg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MBLNR', sa.String(length=10), nullable=False, comment='Material Document Number'),
    sa.Column('MJAHR', sa.String(length=4), nullable=False, comment='Material Document Year'),
    sa.Column('ZEILE', sa.String(length=4), nullable=False, comment='Line Item in Material Document'),
    sa.Column('MATNR', sa.String(length=18), nullable=True, comment='Material Number'),
    sa.Column('WERKS', sa.String(length=4), nullable=True, comment='Plant'),
    sa.Column('MENGE', sa.Float(), nullable=True, comment='Quantity'),
    sa.Column('MEINS', sa.String(length=3), nullable=True, comment='Unit of Measure'),
    sa.Column('EBELN', sa.String(length=10), nullable=True, comment='Purchase Order Number'),
    sa.Column('EBELP', sa.String(length=5), nullable=True, comment='PO Item Number'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('MBLNR', 'MJAHR', 'ZEILE', name='mseg_mblnr_mjahr_zeile_key'),
    schema='sap'
    )
    op.create_table('rseg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Invoice Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BUZEI', sa.String(length=3), nullable=False, comment='Line Item Number'),
    sa.Column('EBELN', sa.String(length=10), nullable=True, comment='Purchase Order Number'),
    sa.Column('EBELP', sa.String(length=5), nullable=True, comment='PO Item Number'),
    sa.Column('MATNR', sa.String(length=18), nullable=True, comment='Material Number'),
    sa.Column('MENGE', sa.Float(), nullable=True, comment='Quantity'),
    sa.Column('WRBTR', sa.Float(), nullable=True, comment='Amount in Document Currency'),
    sa.Column('BWTAR', sa.String(length=10), nullable=True, comment='Valuation Type'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('BELNR', 'GJAHR', 'BUZEI', name='rseg_belnr_gjahr_buzei_key'),
    schema='sap'
    )
    op.create_table('business_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ruleId', sa.String(), nullable=False),
    sa.Column('ruleName', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('ruleType', sa.String(), nullable=False),
    sa.Column('sqlExpression', sa.String(), nullable=True),
    sa.Column('jsonSchema', sa.JSON(), nullable=True),
    sa.Column('aiExplanation', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleId'),
    schema='semantic_layer'
    )
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('businessDefinition', sa.String(), nullable=False),
    sa.Column('businessOwner', sa.String(), nullable=False),
    sa.Column('dataSteward', sa.String(), nullable=False),
    sa.Column('sourceSystem', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('dataClassification', sa.String(), nullable=False),
    sa.Column('complianceTags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('retentionPolicy', sa.String(), nullable=False),
    sa.Column('versionId', sa.String(), nullable=False),
    sa.Column('effectiveFrom', sa.DateTime(), nullable=False),
    sa.Column('effectiveTo', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entityId'),
    schema='semantic_layer'
    )
    op.create_table('vendor_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('embedding', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendorId'),
    schema='vector_layer'
    )
    op.create_table('curated_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoiceId', sa.String(), nullable=False),
    sa.Column('invoiceNumber', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('invoiceDate', sa.DateTime(), nullable=False),
    sa.Column('totalAmount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validTo', sa.DateTime(), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=True),
    sa.Column('dqScore', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendorId'], ['curated_layer.curated_vendors.vendorId'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='curated_layer'
    )
    op.create_table('ekko',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EBELN', sa.String(length=10), nullable=False, comment='Purchase Order Number'),
    sa.Column('BUKRS', sa.String(length=4), nullable=True, comment='Company Code'),
    sa.Column('LIFNR', sa.String(length=10), nullable=True, comment='Vendor Number'),
    sa.Column('BEDAT', sa.Date(), nullable=True, comment='Purchase Order Date'),
    sa.Column('WAERS', sa.String(length=5), nullable=True, comment='Currency Key'),
    sa.Column('NETWR', sa.Float(), nullable=True, comment='Net Order Value'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['LIFNR'], ['sap.lfa1.LIFNR'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EBELN'),
    schema='sap'
    )
    op.create_table('lfb1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LIFNR', sa.String(length=10), nullable=False, comment='Vendor Number'),
    sa.Column('BUKRS', sa.String(length=4), nullable=False, comment='Company Code'),
    sa.Column('AKONT', sa.String(length=10), nullable=True, comment='Reconciliation Account'),
    sa.Column('ZTERM', sa.String(length=4), nullable=True, comment='Payment Terms Key'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['LIFNR'], ['sap.lfa1.LIFNR'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('LIFNR', 'BUKRS', name='lfb1_lifnr_bukrs_key'),
    schema='sap'
    )
    op.create_table('rbkp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BLDAT', sa.Date(), nullable=True, comment='Document Date'),
    sa.Column('BUDAT', sa.Date(), nullable=True, comment='Posting Date'),
    sa.Column('LIFNR', sa.String(length=10), nullable=True, comment='Vendor Number'),
    sa.Column('XBLNR', sa.String(length=16), nullable=True, comment='Reference Document Number'),
    sa.Column('WAERS', sa.String(length=5), nullable=True, comment='Currency Key'),
    sa.Column('RMWWR', sa.Float(), nullable=True, comment='Gross Invoice Amount'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['LIFNR'], ['sap.lfa1.LIFNR'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('BELNR', 'GJAHR', name='rbkp_belnr_gjahr_key'),
    schema='sap'
    )
    op.create_table('attributes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attributeId', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=False),
    sa.Column('attributeName', sa.String(), nullable=False),
    sa.Column('dataType', sa.String(), nullable=False),
    sa.Column('businessDefinition', sa.String(), nullable=False),
    sa.Column('isSensitive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityId'], ['semantic_layer.entities.entityId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attributeId'),
    schema='semantic_layer'
    )
    op.create_table('ekpo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EBELN', sa.String(length=10), nullable=False, comment='Purchase Order Number'),
    sa.Column('EBELP', sa.String(length=5), nullable=False, comment='PO Item Number'),
    sa.Column('MATNR', sa.String(length=18), nullable=True, comment='Material Number'),
    sa.Column('MENGE', sa.Float(), nullable=True, comment='Purchase Order Quantity'),
    sa.Column('MEINS', sa.String(length=3), nullable=True, comment='Unit of Measure'),
    sa.Column('NETPR', sa.Float(), nullable=True, comment='Net Price'),
    sa.Column('NETWR', sa.Float(), nullable=True, comment='Net Order Value'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['EBELN'], ['sap.ekko.EBELN'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EBELN', 'EBELP', name='ekpo_ebeln_ebelp_key'),
    schema='sap'
    )
    op.drop_index(op.f('ix_test_id'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pkey')),
    sa.UniqueConstraint('email', name=op.f('test_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_test_id'), 'test', ['id'], unique=False)
    op.drop_table('ekpo', schema='sap')
    op.drop_table('attributes', schema='semantic_layer')
    op.drop_table('rbkp', schema='sap')
    op.drop_table('lfb1', schema='sap')
    op.drop_table('ekko', schema='sap')
    op.drop_table('curated_invoices', schema='curated_layer')
    op.drop_table('vendor_embeddings', schema='vector_layer')
    op.drop_table('entities', schema='semantic_layer')
    op.drop_table('business_rules', schema='semantic_layer')
    op.drop_table('rseg', schema='sap')
    op.drop_table('mseg', schema='sap')
    op.drop_table('mkpf', schema='sap')
    op.drop_table('lfa1', schema='sap')
    op.drop_table('bseg', schema='sap')
    op.drop_table('bkpf', schema='sap')
    op.drop_table('push_queue', schema='push_layer')
    op.drop_table('extraction_metadata', schema='integration_layer')
    op.drop_table('events', schema='event_store')
    op.drop_table('dq_scores', schema='dq_layer')
    op.drop_table('curated_vendors', schema='curated_layer')
    op.drop_table('data_change_logs', schema='audit_layer')
    op.drop_table('data_access_logs', schema='audit_layer')
    op.drop_table('ai_action_logs', schema='audit_layer')
    op.drop_index(op.f('ix_ai_synthetic_data_id'), table_name='synthetic_data', schema='ai')
    op.drop_table('synthetic_data', schema='ai')
    # ### end Alembic commands ###
