"""final_init

Revision ID: 5d954be544ac
Revises: 
Create Date: 2026-02-18 16:00:09.692134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d954be544ac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_action_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actionId', sa.String(), nullable=False),
    sa.Column('agentName', sa.String(), nullable=False),
    sa.Column('actionType', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=True),
    sa.Column('inputData', sa.JSON(), nullable=True),
    sa.Column('outputData', sa.JSON(), nullable=True),
    sa.Column('confidenceScore', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.String(), nullable=True),
    sa.Column('executedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actionId'),
    schema='audit_layer'
    )
    op.create_table('data_access_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('accessedBy', sa.String(), nullable=False),
    sa.Column('accessedByType', sa.String(), nullable=False),
    sa.Column('accessedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='audit_layer'
    )
    op.create_table('data_change_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('oldValue', sa.JSON(), nullable=True),
    sa.Column('newValue', sa.JSON(), nullable=True),
    sa.Column('changedBy', sa.String(), nullable=False),
    sa.Column('changedByType', sa.String(), nullable=False),
    sa.Column('changedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='audit_layer'
    )
    op.create_table('curated_vendors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('vendorCode', sa.String(), nullable=False),
    sa.Column('vendorName', sa.String(), nullable=False),
    sa.Column('gst', sa.String(), nullable=True),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validTo', sa.DateTime(), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=True),
    sa.Column('dqScore', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('nameiy', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendorId'),
    schema='curated_layer'
    )
    op.create_table('dq_scores',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('recordId', sa.String(), nullable=True),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('consistency', sa.Float(), nullable=True),
    sa.Column('validity', sa.Float(), nullable=True),
    sa.Column('timeliness', sa.Float(), nullable=True),
    sa.Column('uniqueness', sa.Float(), nullable=True),
    sa.Column('compositeScore', sa.Float(), nullable=False),
    sa.Column('measuredAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dq_layer'
    )
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('eventId', sa.String(), nullable=False),
    sa.Column('eventType', sa.String(), nullable=False),
    sa.Column('aggregateId', sa.String(), nullable=False),
    sa.Column('aggregateType', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('correlationId', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventId'),
    schema='event_store'
    )
    op.create_table('extraction_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('extractionId', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('extractionType', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recordsExtracted', sa.Integer(), nullable=True),
    sa.Column('recordsFailed', sa.Integer(), nullable=True),
    sa.Column('startedAt', sa.DateTime(), nullable=False),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extractionId'),
    schema='integration_layer'
    )
    op.create_table('push_queue',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('queueId', sa.String(), nullable=False),
    sa.Column('targetSystem', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('operation', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('retryCount', sa.Integer(), nullable=True),
    sa.Column('maxRetries', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('processedAt', sa.DateTime(), nullable=True),
    sa.Column('completedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('queueId'),
    schema='push_layer'
    )
    op.create_table('business_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ruleId', sa.String(), nullable=False),
    sa.Column('ruleName', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('ruleType', sa.String(), nullable=False),
    sa.Column('sqlExpression', sa.String(), nullable=True),
    sa.Column('jsonSchema', sa.JSON(), nullable=True),
    sa.Column('aiExplanation', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdBy', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleId'),
    schema='semantic_layer'
    )
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=False),
    sa.Column('entityName', sa.String(), nullable=False),
    sa.Column('businessDefinition', sa.String(), nullable=False),
    sa.Column('businessOwner', sa.String(), nullable=False),
    sa.Column('dataSteward', sa.String(), nullable=False),
    sa.Column('sourceSystem', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('dataClassification', sa.String(), nullable=False),
    sa.Column('complianceTags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('retentionPolicy', sa.String(), nullable=False),
    sa.Column('versionId', sa.String(), nullable=False),
    sa.Column('effectiveFrom', sa.DateTime(), nullable=False),
    sa.Column('effectiveTo', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entityId'),
    schema='semantic_layer'
    )
    op.create_table('vendor_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('embedding', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendorId'),
    schema='vector_layer'
    )
    op.create_table('curated_invoices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('invoiceId', sa.String(), nullable=False),
    sa.Column('invoiceNumber', sa.String(), nullable=False),
    sa.Column('vendorId', sa.String(), nullable=False),
    sa.Column('invoiceDate', sa.DateTime(), nullable=False),
    sa.Column('totalAmount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validTo', sa.DateTime(), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=True),
    sa.Column('dqScore', sa.Float(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendorId'], ['curated_layer.curated_vendors.vendorId'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='curated_layer'
    )
    op.create_table('attributes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attributeId', sa.String(), nullable=False),
    sa.Column('entityId', sa.String(), nullable=False),
    sa.Column('attributeName', sa.String(), nullable=False),
    sa.Column('dataType', sa.String(), nullable=False),
    sa.Column('businessDefinition', sa.String(), nullable=False),
    sa.Column('isSensitive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entityId'], ['semantic_layer.entities.entityId'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attributeId'),
    schema='semantic_layer'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attributes', schema='semantic_layer')
    op.drop_table('curated_invoices', schema='curated_layer')
    op.drop_table('vendor_embeddings', schema='vector_layer')
    op.drop_table('entities', schema='semantic_layer')
    op.drop_table('business_rules', schema='semantic_layer')
    op.drop_table('push_queue', schema='push_layer')
    op.drop_table('extraction_metadata', schema='integration_layer')
    op.drop_table('events', schema='event_store')
    op.drop_table('dq_scores', schema='dq_layer')
    op.drop_table('curated_vendors', schema='curated_layer')
    op.drop_table('data_change_logs', schema='audit_layer')
    op.drop_table('data_access_logs', schema='audit_layer')
    op.drop_table('ai_action_logs', schema='audit_layer')
    # ### end Alembic commands ###
