"""expand_sap_tables_realistic

Revision ID: 8af70eb52bbf
Revises: faeded992b93
Create Date: 2026-02-21 19:12:08.648929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af70eb52bbf'
down_revision: Union[str, None] = 'faeded992b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bkpf', sa.Column('BLDAT', sa.Date(), nullable=True, comment='Document Date in Document'), schema='sap')
    op.add_column('bkpf', sa.Column('MONAT', sa.Integer(), nullable=True, comment='Fiscal Period'), schema='sap')
    op.add_column('bkpf', sa.Column('CPUTM', sa.DateTime(), nullable=True, comment='Time of Entry'), schema='sap')
    op.add_column('bkpf', sa.Column('AEDAT', sa.Date(), nullable=True, comment='Date of the Last Document Change'), schema='sap')
    op.add_column('bkpf', sa.Column('UPDDT', sa.Date(), nullable=True, comment='Date of the Last Update'), schema='sap')
    op.add_column('bkpf', sa.Column('WWERT', sa.Date(), nullable=True, comment='Translation date'), schema='sap')
    op.add_column('bkpf', sa.Column('TCODE', sa.String(length=20), nullable=True, comment='Transaction Code'), schema='sap')
    op.add_column('bkpf', sa.Column('BVORG', sa.String(length=16), nullable=True, comment='Number of a Cross-Company Code Transaction'), schema='sap')
    op.add_column('bkpf', sa.Column('XBLNR', sa.String(length=16), nullable=True, comment='Reference Document Number'), schema='sap')
    op.add_column('bkpf', sa.Column('DBBLG', sa.String(length=10), nullable=True, comment='Recurring entry document number'), schema='sap')
    op.add_column('bkpf', sa.Column('STBLG', sa.String(length=10), nullable=True, comment='Reverse Document Number'), schema='sap')
    op.add_column('bkpf', sa.Column('STJAH', sa.String(length=4), nullable=True, comment='Reverse document fiscal year'), schema='sap')
    op.add_column('bkpf', sa.Column('BKTXT', sa.String(length=25), nullable=True, comment='Document Header Text'), schema='sap')
    op.add_column('bkpf', sa.Column('WAERS', sa.String(length=5), nullable=True, comment='Currency Key'), schema='sap')
    op.add_column('bkpf', sa.Column('KURSF', sa.Float(), nullable=True, comment='Exchange Rate'), schema='sap')
    op.add_column('bkpf', sa.Column('KZWRS', sa.String(length=5), nullable=True, comment='Group Currency'), schema='sap')
    op.alter_column('bkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date in the Document',
               existing_comment='Posting Date',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'CPUDT',
               existing_type=sa.DATE(),
               comment='Day On Which Accounting Document Was Entered',
               existing_comment='Entry Date',
               existing_nullable=True,
               schema='sap')
    op.add_column('bseg', sa.Column('BZIRK', sa.String(length=6), nullable=True, comment='Sales District'), schema='sap')
    op.add_column('bseg', sa.Column('BSCHL', sa.String(length=2), nullable=True, comment='Posting Key'), schema='sap')
    op.add_column('bseg', sa.Column('UMSKZ', sa.String(length=1), nullable=True, comment='Special G/L Indicator'), schema='sap')
    op.add_column('bseg', sa.Column('GSBER', sa.String(length=4), nullable=True, comment='Business Area'), schema='sap')
    op.add_column('bseg', sa.Column('PARGB', sa.String(length=4), nullable=True, comment="Trading partner's business area"), schema='sap')
    op.add_column('bseg', sa.Column('MWSKZ', sa.String(length=2), nullable=True, comment='Tax on sales/purchases code'), schema='sap')
    op.add_column('bseg', sa.Column('MWSTS', sa.Float(), nullable=True, comment='Tax amount in local currency'), schema='sap')
    op.add_column('bseg', sa.Column('WMWST', sa.Float(), nullable=True, comment='Tax amount in document currency'), schema='sap')
    op.add_column('bseg', sa.Column('HWBAS', sa.Float(), nullable=True, comment='Tax base amount in local currency'), schema='sap')
    op.add_column('bseg', sa.Column('FWBAS', sa.Float(), nullable=True, comment='Tax base amount in document currency'), schema='sap')
    op.add_column('bseg', sa.Column('HWZUZ', sa.Float(), nullable=True, comment='Provision amount in local currency'), schema='sap')
    op.add_column('bseg', sa.Column('FWZUZ', sa.Float(), nullable=True, comment='Provision amount in document currency'), schema='sap')
    op.add_column('bseg', sa.Column('KUNNR', sa.String(length=10), nullable=True, comment='Customer Number'), schema='sap')
    op.add_column('bseg', sa.Column('LIFNR', sa.String(length=10), nullable=True, comment='Account Number of Vendor or Creditor'), schema='sap')
    op.add_column('bseg', sa.Column('PROJK', sa.String(length=8), nullable=True, comment='WBS Element'), schema='sap')
    op.add_column('bseg', sa.Column('AUFNR', sa.String(length=12), nullable=True, comment='Order Number'), schema='sap')
    op.add_column('ekko', sa.Column('BSTYP', sa.String(length=1), nullable=True, comment='Purchasing Document Category'), schema='sap')
    op.add_column('ekko', sa.Column('BSART', sa.String(length=4), nullable=True, comment='Purchasing Document Type'), schema='sap')
    op.add_column('ekko', sa.Column('BSAKU', sa.String(length=1), nullable=True, comment='Control indicator'), schema='sap')
    op.add_column('ekko', sa.Column('LOEKZ', sa.String(length=1), nullable=True, comment='Deletion indicator'), schema='sap')
    op.add_column('ekko', sa.Column('STATU', sa.String(length=1), nullable=True, comment='Status of Purchasing Document'), schema='sap')
    op.add_column('ekko', sa.Column('AEDAT', sa.Date(), nullable=True, comment='Date on Which Record Was Created'), schema='sap')
    op.add_column('ekko', sa.Column('ERNAM', sa.String(length=12), nullable=True, comment='Name of Person who Created the Object'), schema='sap')
    op.add_column('ekko', sa.Column('ZTERM', sa.String(length=4), nullable=True, comment='Terms of Payment Key'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD1T', sa.Float(), nullable=True, comment='Cash discount days 1'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD2T', sa.Float(), nullable=True, comment='Cash discount days 2'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD3T', sa.Float(), nullable=True, comment='Cash discount days 3'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD1P', sa.Float(), nullable=True, comment='Cash discount percentage 1'), schema='sap')
    op.add_column('ekko', sa.Column('ZBD2P', sa.Float(), nullable=True, comment='Cash discount percentage 2'), schema='sap')
    op.add_column('ekko', sa.Column('EKORG', sa.String(length=4), nullable=True, comment='Purchasing Organization'), schema='sap')
    op.add_column('ekko', sa.Column('EKGRP', sa.String(length=3), nullable=True, comment='Purchasing Group'), schema='sap')
    op.add_column('ekko', sa.Column('WKURS', sa.Float(), nullable=True, comment='Exchange Rate'), schema='sap')
    op.add_column('ekko', sa.Column('KUFIX', sa.String(length=1), nullable=True, comment='Indicator: Fix exchange rate'), schema='sap')
    op.add_column('ekko', sa.Column('KDATB', sa.Date(), nullable=True, comment='Start of Validity Period'), schema='sap')
    op.add_column('ekko', sa.Column('KDATE', sa.Date(), nullable=True, comment='End of Validity Period'), schema='sap')
    op.add_column('ekko', sa.Column('BWVKO', sa.Date(), nullable=True, comment='Date of last document update'), schema='sap')
    op.add_column('ekko', sa.Column('KNUMV', sa.String(length=10), nullable=True, comment='Number of the document condition'), schema='sap')
    op.add_column('ekko', sa.Column('RESWK', sa.String(length=4), nullable=True, comment='Supplying (issuing) plant'), schema='sap')
    op.add_column('ekko', sa.Column('LPNOH', sa.String(length=10), nullable=True, comment='Last item number'), schema='sap')
    op.add_column('ekko', sa.Column('LIBRE', sa.String(length=1), nullable=True, comment='Release group'), schema='sap')
    op.add_column('ekko', sa.Column('PROCSTAT', sa.String(length=2), nullable=True, comment='Processing State'), schema='sap')
    op.alter_column('ekko', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchasing Document Number',
               existing_comment='Purchase Order Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekko', 'BEDAT',
               existing_type=sa.DATE(),
               comment='Purchasing Document Date',
               existing_comment='Purchase Order Date',
               existing_nullable=True,
               schema='sap')
    op.add_column('ekpo', sa.Column('LOEKZ', sa.String(length=1), nullable=True, comment='Deletion indicator'), schema='sap')
    op.add_column('ekpo', sa.Column('STATU', sa.String(length=1), nullable=True, comment='RFQ status'), schema='sap')
    op.add_column('ekpo', sa.Column('AEDAT', sa.Date(), nullable=True, comment='Purchasing document item change date'), schema='sap')
    op.add_column('ekpo', sa.Column('TXZ01', sa.String(length=40), nullable=True, comment='Short Text'), schema='sap')
    op.add_column('ekpo', sa.Column('EMATN', sa.String(length=18), nullable=True, comment='Material number'), schema='sap')
    op.add_column('ekpo', sa.Column('BUKRS', sa.String(length=4), nullable=True, comment='Company Code'), schema='sap')
    op.add_column('ekpo', sa.Column('WERKS', sa.String(length=4), nullable=True, comment='Plant'), schema='sap')
    op.add_column('ekpo', sa.Column('LGORT', sa.String(length=4), nullable=True, comment='Storage Location'), schema='sap')
    op.add_column('ekpo', sa.Column('BEDNR', sa.String(length=10), nullable=True, comment='Requirement Tracking Number'), schema='sap')
    op.add_column('ekpo', sa.Column('MATKL', sa.String(length=9), nullable=True, comment='Material Group'), schema='sap')
    op.add_column('ekpo', sa.Column('BPUMZ', sa.Float(), nullable=True, comment='Numerator for Conversion of Order Unit to Base Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('BPUMN', sa.Float(), nullable=True, comment='Denominator for Conv. of Order Unit to Base Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('PEINH', sa.Float(), nullable=True, comment='Price Unit'), schema='sap')
    op.add_column('ekpo', sa.Column('BRTWR', sa.Float(), nullable=True, comment='Gross order value'), schema='sap')
    op.add_column('ekpo', sa.Column('AGDAT', sa.Date(), nullable=True, comment='Deadline for Submission of Quotation'), schema='sap')
    op.add_column('ekpo', sa.Column('WEBAZ', sa.Float(), nullable=True, comment='Goods receipt processing time'), schema='sap')
    op.add_column('ekpo', sa.Column('MWSKZ', sa.String(length=2), nullable=True, comment='Tax on sales/purchases code'), schema='sap')
    op.add_column('ekpo', sa.Column('BONUS', sa.String(length=2), nullable=True, comment='Settlement Group'), schema='sap')
    op.add_column('ekpo', sa.Column('INSMK', sa.String(length=1), nullable=True, comment='Stock Type'), schema='sap')
    op.add_column('ekpo', sa.Column('SPINF', sa.Boolean(), nullable=True, comment='Indicator: Update Info Record'), schema='sap')
    op.add_column('ekpo', sa.Column('PRSDR', sa.Boolean(), nullable=True, comment='Print Price'), schema='sap')
    op.add_column('ekpo', sa.Column('BWTAR', sa.String(length=10), nullable=True, comment='Valuation Type'), schema='sap')
    op.add_column('ekpo', sa.Column('BWTTY', sa.String(length=1), nullable=True, comment='Valuation Category'), schema='sap')
    op.add_column('ekpo', sa.Column('ABSKZ', sa.String(length=1), nullable=True, comment='Rejection Indicator'), schema='sap')
    op.alter_column('ekpo', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchasing Document Number',
               existing_comment='Purchase Order Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekpo', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment='Item Number of Purchasing Document',
               existing_comment='PO Item Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekpo', 'MEINS',
               existing_type=sa.VARCHAR(length=3),
               comment='Order Unit',
               existing_comment='Unit of Measure',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'NETPR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Price in Purchasing Document',
               existing_comment='Net Price',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'NETWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Order Value in PO Currency',
               existing_comment='Net Order Value',
               existing_nullable=True,
               schema='sap')
    op.add_column('lfa1', sa.Column('NAME2', sa.String(length=35), nullable=True, comment='Name 2'), schema='sap')
    op.add_column('lfa1', sa.Column('NAME3', sa.String(length=35), nullable=True, comment='Name 3'), schema='sap')
    op.add_column('lfa1', sa.Column('NAME4', sa.String(length=35), nullable=True, comment='Name 4'), schema='sap')
    op.add_column('lfa1', sa.Column('CITY1', sa.String(length=35), nullable=True, comment='City'), schema='sap')
    op.add_column('lfa1', sa.Column('POST_CODE1', sa.String(length=10), nullable=True, comment='Postal Code'), schema='sap')
    op.add_column('lfa1', sa.Column('STREET', sa.String(length=35), nullable=True, comment='Street'), schema='sap')
    op.add_column('lfa1', sa.Column('HOUSE_NUM1', sa.String(length=10), nullable=True, comment='House Number'), schema='sap')
    op.add_column('lfa1', sa.Column('COUNTRY', sa.String(length=3), nullable=True, comment='Country Key'), schema='sap')
    op.add_column('lfa1', sa.Column('REGION', sa.String(length=3), nullable=True, comment='Region (State)'), schema='sap')
    op.add_column('lfa1', sa.Column('TELF1', sa.String(length=16), nullable=True, comment='First Telephone Number'), schema='sap')
    op.add_column('lfa1', sa.Column('TELF2', sa.String(length=16), nullable=True, comment='Second Telephone Number'), schema='sap')
    op.add_column('lfa1', sa.Column('TELFX', sa.String(length=31), nullable=True, comment='Fax Number'), schema='sap')
    op.add_column('lfa1', sa.Column('TELTX', sa.String(length=30), nullable=True, comment='Teletex Number'), schema='sap')
    op.add_column('lfa1', sa.Column('TELX1', sa.String(length=30), nullable=True, comment='Telex Number'), schema='sap')
    op.add_column('lfa1', sa.Column('SMTP_ADDR', sa.String(length=241), nullable=True, comment='E-Mail Address'), schema='sap')
    op.add_column('lfa1', sa.Column('LANGU', sa.String(length=2), nullable=True, comment='Language Key'), schema='sap')
    op.add_column('lfa1', sa.Column('STCD2', sa.String(length=11), nullable=True, comment='Tax Number 2'), schema='sap')
    op.add_column('lfa1', sa.Column('STCD3', sa.String(length=18), nullable=True, comment='Tax Number 3'), schema='sap')
    op.add_column('lfa1', sa.Column('STCEG', sa.String(length=20), nullable=True, comment='VAT Registration Number'), schema='sap')
    op.add_column('lfa1', sa.Column('BRSCH', sa.String(length=4), nullable=True, comment='Industry Key'), schema='sap')
    op.add_column('lfa1', sa.Column('KONZS', sa.String(length=10), nullable=True, comment='Group Key'), schema='sap')
    op.add_column('lfa1', sa.Column('VBUND', sa.String(length=6), nullable=True, comment='Trading Partner'), schema='sap')
    op.add_column('lfa1', sa.Column('ERDAT', sa.Date(), nullable=True, comment='Date on which record was created'), schema='sap')
    op.add_column('lfa1', sa.Column('ERNAM', sa.String(length=12), nullable=True, comment='Name of Person who Created the Object'), schema='sap')
    op.add_column('lfa1', sa.Column('SPERR', sa.Boolean(), nullable=True, comment='Central Posting Block'), schema='sap')
    op.add_column('lfa1', sa.Column('SPERZ', sa.Boolean(), nullable=True, comment='Payment Block'), schema='sap')
    op.add_column('lfa1', sa.Column('LOEVM', sa.Boolean(), nullable=True, comment='Central Deletion Flag'), schema='sap')
    op.add_column('lfa1', sa.Column('UPDAT', sa.Date(), nullable=True, comment='Date of Last Update'), schema='sap')
    op.add_column('lfa1', sa.Column('UPTIM', sa.DateTime(), nullable=True, comment='Time of last update'), schema='sap')
    op.add_column('lfa1', sa.Column('MBRSH', sa.String(length=1), nullable=True, comment='Industry Sector'), schema='sap')
    op.add_column('lfa1', sa.Column('FISKN', sa.String(length=10), nullable=True, comment='Account number of the master record'), schema='sap')
    op.alter_column('lfa1', 'NAME1',
               existing_type=sa.VARCHAR(length=35),
               comment='Name 1',
               existing_comment='Vendor Name',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'STCD1',
               existing_type=sa.VARCHAR(length=16),
               comment='Tax Number 1 (GST)',
               existing_comment='Tax Number 1 (GST/VAT)',
               existing_nullable=True,
               schema='sap')
    op.drop_column('lfa1', 'LAND1', schema='sap')
    op.add_column('lfb1', sa.Column('PERNR', sa.String(length=8), nullable=True, comment='Personnel Number'), schema='sap')
    op.add_column('lfb1', sa.Column('ERDAT', sa.Date(), nullable=True, comment='Date on which record was created'), schema='sap')
    op.add_column('lfb1', sa.Column('ERNAM', sa.String(length=12), nullable=True, comment='Name of Person who Created the Object'), schema='sap')
    op.add_column('lfb1', sa.Column('SPERR', sa.Boolean(), nullable=True, comment='Posting block for company code'), schema='sap')
    op.add_column('lfb1', sa.Column('LOEVM', sa.Boolean(), nullable=True, comment='Deletion Flag for Company Code'), schema='sap')
    op.add_column('lfb1', sa.Column('BEGRU', sa.String(length=4), nullable=True, comment='Authorization Group'), schema='sap')
    op.add_column('lfb1', sa.Column('VZSKZ', sa.String(length=2), nullable=True, comment='Interest calculation indicator'), schema='sap')
    op.add_column('lfb1', sa.Column('ZWELS', sa.String(length=10), nullable=True, comment='List of Respected Payment Methods'), schema='sap')
    op.add_column('lfb1', sa.Column('PAY_TYPE', sa.String(length=1), nullable=True, comment='Payment Type'), schema='sap')
    op.add_column('lfb1', sa.Column('ZINDT', sa.Date(), nullable=True, comment='Date of last interest calculation'), schema='sap')
    op.add_column('lfb1', sa.Column('ZINRT', sa.Integer(), nullable=True, comment='Interest calculation frequency'), schema='sap')
    op.add_column('lfb1', sa.Column('EIKTO', sa.String(length=12), nullable=True, comment='Our account number with the vendor'), schema='sap')
    op.add_column('lfb1', sa.Column('ZSABE', sa.String(length=15), nullable=True, comment='Clerk at vendor'), schema='sap')
    op.add_column('lfb1', sa.Column('KVERM', sa.String(length=30), nullable=True, comment='Memo'), schema='sap')
    op.add_column('lfb1', sa.Column('FDGRV', sa.String(length=10), nullable=True, comment='Planning group'), schema='sap')
    op.add_column('lfb1', sa.Column('BUSAB', sa.String(length=2), nullable=True, comment='Accounting clerk'), schema='sap')
    op.add_column('lfb1', sa.Column('LNRZE', sa.String(length=10), nullable=True, comment='Head office account number'), schema='sap')
    op.add_column('lfb1', sa.Column('LNRZB', sa.String(length=10), nullable=True, comment='Alternative payee'), schema='sap')
    op.add_column('lfb1', sa.Column('ZAMNR', sa.String(length=10), nullable=True, comment='Ad-hoc agent'), schema='sap')
    op.add_column('lfb1', sa.Column('ZUAWA', sa.String(length=3), nullable=True, comment='Key for sorting according to assignment numbers'), schema='sap')
    op.add_column('lfb1', sa.Column('ZHBKLS', sa.String(length=5), nullable=True, comment='House Bank'), schema='sap')
    op.add_column('lfb1', sa.Column('XVERR', sa.Boolean(), nullable=True, comment='Clearing with customer'), schema='sap')
    op.add_column('lfb1', sa.Column('ZGRUP', sa.String(length=2), nullable=True, comment='Payment grouping'), schema='sap')
    op.alter_column('lfb1', 'ZTERM',
               existing_type=sa.VARCHAR(length=4),
               comment='Terms of Payment Key',
               existing_comment='Payment Terms Key',
               existing_nullable=True,
               schema='sap')
    op.add_column('mkpf', sa.Column('VGART', sa.String(length=2), nullable=True, comment='Transaction/Event Type'), schema='sap')
    op.add_column('mkpf', sa.Column('BLART', sa.String(length=2), nullable=True, comment='Document Type'), schema='sap')
    op.add_column('mkpf', sa.Column('CPUDT', sa.Date(), nullable=True, comment='Day On Which Accounting Document Was Entered'), schema='sap')
    op.add_column('mkpf', sa.Column('CPUTM', sa.DateTime(), nullable=True, comment='Time of Entry'), schema='sap')
    op.add_column('mkpf', sa.Column('AEDAT', sa.Date(), nullable=True, comment='Date of the Last Document Change'), schema='sap')
    op.add_column('mkpf', sa.Column('TCODE', sa.String(length=20), nullable=True, comment='Transaction Code'), schema='sap')
    op.add_column('mkpf', sa.Column('XBLNR', sa.String(length=16), nullable=True, comment='Reference Document Number'), schema='sap')
    op.add_column('mkpf', sa.Column('BKTXT', sa.String(length=25), nullable=True, comment='Document Header Text'), schema='sap')
    op.alter_column('mkpf', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Number of Material Document',
               existing_comment='Material Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mkpf', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date in Document',
               existing_comment='Document Date',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date in the Document',
               existing_comment='Posting Date',
               existing_nullable=True,
               schema='sap')
    op.add_column('mseg', sa.Column('BWART', sa.String(length=3), nullable=True, comment='Movement Type (Inventory Management)'), schema='sap')
    op.add_column('mseg', sa.Column('LGORT', sa.String(length=4), nullable=True, comment='Storage Location'), schema='sap')
    op.add_column('mseg', sa.Column('CHARG', sa.String(length=10), nullable=True, comment='Batch Number'), schema='sap')
    op.add_column('mseg', sa.Column('INSMK', sa.String(length=1), nullable=True, comment='Stock Type'), schema='sap')
    op.add_column('mseg', sa.Column('ZUGIU', sa.String(length=1), nullable=True, comment='Posting to Stock in Quality Inspection'), schema='sap')
    op.add_column('mseg', sa.Column('SOBKZ', sa.String(length=1), nullable=True, comment='Special Stock Indicator'), schema='sap')
    op.add_column('mseg', sa.Column('LIFNR', sa.String(length=10), nullable=True, comment='Vendor number'), schema='sap')
    op.add_column('mseg', sa.Column('KUNNR', sa.String(length=10), nullable=True, comment='Account number of customer'), schema='sap')
    op.add_column('mseg', sa.Column('KOKRS', sa.String(length=4), nullable=True, comment='Controlling Area'), schema='sap')
    op.add_column('mseg', sa.Column('KOSTL', sa.String(length=10), nullable=True, comment='Cost Center'), schema='sap')
    op.add_column('mseg', sa.Column('PROJK', sa.String(length=8), nullable=True, comment='WBS Element'), schema='sap')
    op.add_column('mseg', sa.Column('AUFNR', sa.String(length=12), nullable=True, comment='Order Number'), schema='sap')
    op.add_column('mseg', sa.Column('ANLN1', sa.String(length=12), nullable=True, comment='Main Asset Number'), schema='sap')
    op.add_column('mseg', sa.Column('ANLN2', sa.String(length=4), nullable=True, comment='Asset Subnumber'), schema='sap')
    op.add_column('mseg', sa.Column('ERFMG', sa.Float(), nullable=True, comment='Quantity in unit of entry'), schema='sap')
    op.add_column('mseg', sa.Column('ERFME', sa.String(length=3), nullable=True, comment='Unit of entry'), schema='sap')
    op.add_column('mseg', sa.Column('LFBJA', sa.String(length=4), nullable=True, comment='Fiscal year of a reference document'), schema='sap')
    op.add_column('mseg', sa.Column('LFBNR', sa.String(length=10), nullable=True, comment='Document number of a reference document'), schema='sap')
    op.add_column('mseg', sa.Column('LFPOS', sa.String(length=4), nullable=True, comment='Item of a reference document'), schema='sap')
    op.add_column('mseg', sa.Column('SJAHR', sa.String(length=4), nullable=True, comment='Material document year'), schema='sap')
    op.add_column('mseg', sa.Column('SMBLN', sa.String(length=10), nullable=True, comment='Number of material document'), schema='sap')
    op.add_column('mseg', sa.Column('SMBLP', sa.String(length=4), nullable=True, comment='Item in material document'), schema='sap')
    op.alter_column('mseg', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Number of Material Document',
               existing_comment='Material Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'ZEILE',
               existing_type=sa.VARCHAR(length=4),
               comment='Item in Material Document',
               existing_comment='Line Item in Material Document',
               existing_nullable=False,
               schema='sap')
    op.add_column('rbkp', sa.Column('BLART', sa.String(length=2), nullable=True, comment='Document Type'), schema='sap')
    op.add_column('rbkp', sa.Column('CPUDT', sa.Date(), nullable=True, comment='Day On Which Accounting Document Was Entered'), schema='sap')
    op.add_column('rbkp', sa.Column('CPUTM', sa.DateTime(), nullable=True, comment='Time of Entry'), schema='sap')
    op.add_column('rbkp', sa.Column('USNAM', sa.String(length=12), nullable=True, comment='User Name'), schema='sap')
    op.add_column('rbkp', sa.Column('TCODE', sa.String(length=20), nullable=True, comment='Transaction Code'), schema='sap')
    op.add_column('rbkp', sa.Column('KURSF', sa.Float(), nullable=True, comment='Exchange Rate'), schema='sap')
    op.add_column('rbkp', sa.Column('WWERT', sa.Date(), nullable=True, comment='Translation date'), schema='sap')
    op.add_column('rbkp', sa.Column('BUKRS', sa.String(length=4), nullable=True, comment='Company Code'), schema='sap')
    op.add_column('rbkp', sa.Column('BEZNK', sa.Float(), nullable=True, comment='Unplanned delivery costs'), schema='sap')
    op.add_column('rbkp', sa.Column('WMWST', sa.Float(), nullable=True, comment='Tax amount in document currency'), schema='sap')
    op.add_column('rbkp', sa.Column('MWSKZ', sa.String(length=2), nullable=True, comment='Tax code'), schema='sap')
    op.add_column('rbkp', sa.Column('ZTERM', sa.String(length=4), nullable=True, comment='Terms of Payment Key'), schema='sap')
    op.add_column('rbkp', sa.Column('ZFBDT', sa.Date(), nullable=True, comment='Baseline Date for Due Date Calculation'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD1T', sa.Float(), nullable=True, comment='Cash discount days 1'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD2T', sa.Float(), nullable=True, comment='Cash discount days 2'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD3T', sa.Float(), nullable=True, comment='Cash discount days 3'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD1P', sa.Float(), nullable=True, comment='Cash discount percentage 1'), schema='sap')
    op.add_column('rbkp', sa.Column('ZBD2P', sa.Float(), nullable=True, comment='Cash discount percentage 2'), schema='sap')
    op.add_column('rbkp', sa.Column('DIEKZ', sa.String(length=1), nullable=True, comment='Service indicator'), schema='sap')
    op.add_column('rbkp', sa.Column('LANDL', sa.String(length=3), nullable=True, comment='Country of supplying country'), schema='sap')
    op.add_column('rbkp', sa.Column('LZBKZ', sa.String(length=3), nullable=True, comment='State central bank indicator'), schema='sap')
    op.add_column('rbkp', sa.Column('STCEG', sa.String(length=20), nullable=True, comment='VAT Registration Number'), schema='sap')
    op.alter_column('rbkp', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Document Number of an Invoice Document',
               existing_comment='Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rbkp', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date in Document',
               existing_comment='Document Date',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date in the Document',
               existing_comment='Posting Date',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Tax Number 1',
               existing_comment='Vendor Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'RMWWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Gross Invoice Amount in Document Currency',
               existing_comment='Gross Invoice Amount',
               existing_nullable=True,
               schema='sap')
    op.add_column('rseg', sa.Column('ZEKKN', sa.String(length=2), nullable=True, comment='Sequential number of account assignment'), schema='sap')
    op.add_column('rseg', sa.Column('BWKEY', sa.String(length=4), nullable=True, comment='Valuation Area'), schema='sap')
    op.add_column('rseg', sa.Column('BUKRS', sa.String(length=4), nullable=True, comment='Company Code'), schema='sap')
    op.add_column('rseg', sa.Column('WERKS', sa.String(length=4), nullable=True, comment='Plant'), schema='sap')
    op.add_column('rseg', sa.Column('SHKZG', sa.String(length=1), nullable=True, comment='Debit/Credit Indicator'), schema='sap')
    op.add_column('rseg', sa.Column('MWSKZ', sa.String(length=2), nullable=True, comment='Tax on sales/purchases code'), schema='sap')
    op.add_column('rseg', sa.Column('TXJCD', sa.String(length=15), nullable=True, comment='Tax Jur.'), schema='sap')
    op.add_column('rseg', sa.Column('BSTME', sa.String(length=3), nullable=True, comment='Purchase order unit of measure'), schema='sap')
    op.add_column('rseg', sa.Column('BPMNG', sa.Float(), nullable=True, comment='Quantity in Purchase Order Price Unit'), schema='sap')
    op.add_column('rseg', sa.Column('BPRME', sa.String(length=3), nullable=True, comment='Order Price Unit (Purchasing)'), schema='sap')
    op.add_column('rseg', sa.Column('LBKUM', sa.Float(), nullable=True, comment='Total Valuated Stock'), schema='sap')
    op.add_column('rseg', sa.Column('SALK3', sa.Float(), nullable=True, comment='Value of Total Valuated Stock'), schema='sap')
    op.add_column('rseg', sa.Column('VPRSV', sa.String(length=1), nullable=True, comment='Price control indicator'), schema='sap')
    op.add_column('rseg', sa.Column('VERPR', sa.Float(), nullable=True, comment='Moving Average Price/Periodic Unit Price'), schema='sap')
    op.add_column('rseg', sa.Column('STPRS', sa.Float(), nullable=True, comment='Standard price'), schema='sap')
    op.add_column('rseg', sa.Column('PEINH', sa.Float(), nullable=True, comment='Price Unit'), schema='sap')
    op.add_column('rseg', sa.Column('SKFBP', sa.Float(), nullable=True, comment='Amount eligible for cash discount'), schema='sap')
    op.add_column('rseg', sa.Column('KSCHL', sa.String(length=4), nullable=True, comment='Condition Type'), schema='sap')
    op.alter_column('rseg', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Document Number of an Invoice Document',
               existing_comment='Invoice Document Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'BUZEI',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=6),
               comment='Item List Number',
               existing_comment='Line Item Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchasing Document Number',
               existing_comment='Purchase Order Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment='Item Number of Purchasing Document',
               existing_comment='PO Item Number',
               existing_nullable=True,
               schema='sap')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rseg', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment='PO Item Number',
               existing_comment='Item Number of Purchasing Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchase Order Number',
               existing_comment='Purchasing Document Number',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rseg', 'BUZEI',
               existing_type=sa.String(length=6),
               type_=sa.VARCHAR(length=3),
               comment='Line Item Number',
               existing_comment='Item List Number',
               existing_nullable=False,
               schema='sap')
    op.alter_column('rseg', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Invoice Document Number',
               existing_comment='Document Number of an Invoice Document',
               existing_nullable=False,
               schema='sap')
    op.drop_column('rseg', 'KSCHL', schema='sap')
    op.drop_column('rseg', 'SKFBP', schema='sap')
    op.drop_column('rseg', 'PEINH', schema='sap')
    op.drop_column('rseg', 'STPRS', schema='sap')
    op.drop_column('rseg', 'VERPR', schema='sap')
    op.drop_column('rseg', 'VPRSV', schema='sap')
    op.drop_column('rseg', 'SALK3', schema='sap')
    op.drop_column('rseg', 'LBKUM', schema='sap')
    op.drop_column('rseg', 'BPRME', schema='sap')
    op.drop_column('rseg', 'BPMNG', schema='sap')
    op.drop_column('rseg', 'BSTME', schema='sap')
    op.drop_column('rseg', 'TXJCD', schema='sap')
    op.drop_column('rseg', 'MWSKZ', schema='sap')
    op.drop_column('rseg', 'SHKZG', schema='sap')
    op.drop_column('rseg', 'WERKS', schema='sap')
    op.drop_column('rseg', 'BUKRS', schema='sap')
    op.drop_column('rseg', 'BWKEY', schema='sap')
    op.drop_column('rseg', 'ZEKKN', schema='sap')
    op.alter_column('rbkp', 'RMWWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Gross Invoice Amount',
               existing_comment='Gross Invoice Amount in Document Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'LIFNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Vendor Number',
               existing_comment='Tax Number 1',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date',
               existing_comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date',
               existing_comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('rbkp', 'BELNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Document Number',
               existing_comment='Document Number of an Invoice Document',
               existing_nullable=False,
               schema='sap')
    op.drop_column('rbkp', 'STCEG', schema='sap')
    op.drop_column('rbkp', 'LZBKZ', schema='sap')
    op.drop_column('rbkp', 'LANDL', schema='sap')
    op.drop_column('rbkp', 'DIEKZ', schema='sap')
    op.drop_column('rbkp', 'ZBD2P', schema='sap')
    op.drop_column('rbkp', 'ZBD1P', schema='sap')
    op.drop_column('rbkp', 'ZBD3T', schema='sap')
    op.drop_column('rbkp', 'ZBD2T', schema='sap')
    op.drop_column('rbkp', 'ZBD1T', schema='sap')
    op.drop_column('rbkp', 'ZFBDT', schema='sap')
    op.drop_column('rbkp', 'ZTERM', schema='sap')
    op.drop_column('rbkp', 'MWSKZ', schema='sap')
    op.drop_column('rbkp', 'WMWST', schema='sap')
    op.drop_column('rbkp', 'BEZNK', schema='sap')
    op.drop_column('rbkp', 'BUKRS', schema='sap')
    op.drop_column('rbkp', 'WWERT', schema='sap')
    op.drop_column('rbkp', 'KURSF', schema='sap')
    op.drop_column('rbkp', 'TCODE', schema='sap')
    op.drop_column('rbkp', 'USNAM', schema='sap')
    op.drop_column('rbkp', 'CPUTM', schema='sap')
    op.drop_column('rbkp', 'CPUDT', schema='sap')
    op.drop_column('rbkp', 'BLART', schema='sap')
    op.alter_column('mseg', 'ZEILE',
               existing_type=sa.VARCHAR(length=4),
               comment='Line Item in Material Document',
               existing_comment='Item in Material Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('mseg', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Material Document Number',
               existing_comment='Number of Material Document',
               existing_nullable=False,
               schema='sap')
    op.drop_column('mseg', 'SMBLP', schema='sap')
    op.drop_column('mseg', 'SMBLN', schema='sap')
    op.drop_column('mseg', 'SJAHR', schema='sap')
    op.drop_column('mseg', 'LFPOS', schema='sap')
    op.drop_column('mseg', 'LFBNR', schema='sap')
    op.drop_column('mseg', 'LFBJA', schema='sap')
    op.drop_column('mseg', 'ERFME', schema='sap')
    op.drop_column('mseg', 'ERFMG', schema='sap')
    op.drop_column('mseg', 'ANLN2', schema='sap')
    op.drop_column('mseg', 'ANLN1', schema='sap')
    op.drop_column('mseg', 'AUFNR', schema='sap')
    op.drop_column('mseg', 'PROJK', schema='sap')
    op.drop_column('mseg', 'KOSTL', schema='sap')
    op.drop_column('mseg', 'KOKRS', schema='sap')
    op.drop_column('mseg', 'KUNNR', schema='sap')
    op.drop_column('mseg', 'LIFNR', schema='sap')
    op.drop_column('mseg', 'SOBKZ', schema='sap')
    op.drop_column('mseg', 'ZUGIU', schema='sap')
    op.drop_column('mseg', 'INSMK', schema='sap')
    op.drop_column('mseg', 'CHARG', schema='sap')
    op.drop_column('mseg', 'LGORT', schema='sap')
    op.drop_column('mseg', 'BWART', schema='sap')
    op.alter_column('mkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date',
               existing_comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'BLDAT',
               existing_type=sa.DATE(),
               comment='Document Date',
               existing_comment='Document Date in Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('mkpf', 'MBLNR',
               existing_type=sa.VARCHAR(length=10),
               comment='Material Document Number',
               existing_comment='Number of Material Document',
               existing_nullable=False,
               schema='sap')
    op.drop_column('mkpf', 'BKTXT', schema='sap')
    op.drop_column('mkpf', 'XBLNR', schema='sap')
    op.drop_column('mkpf', 'TCODE', schema='sap')
    op.drop_column('mkpf', 'AEDAT', schema='sap')
    op.drop_column('mkpf', 'CPUTM', schema='sap')
    op.drop_column('mkpf', 'CPUDT', schema='sap')
    op.drop_column('mkpf', 'BLART', schema='sap')
    op.drop_column('mkpf', 'VGART', schema='sap')
    op.alter_column('lfb1', 'ZTERM',
               existing_type=sa.VARCHAR(length=4),
               comment='Payment Terms Key',
               existing_comment='Terms of Payment Key',
               existing_nullable=True,
               schema='sap')
    op.drop_column('lfb1', 'ZGRUP', schema='sap')
    op.drop_column('lfb1', 'XVERR', schema='sap')
    op.drop_column('lfb1', 'ZHBKLS', schema='sap')
    op.drop_column('lfb1', 'ZUAWA', schema='sap')
    op.drop_column('lfb1', 'ZAMNR', schema='sap')
    op.drop_column('lfb1', 'LNRZB', schema='sap')
    op.drop_column('lfb1', 'LNRZE', schema='sap')
    op.drop_column('lfb1', 'BUSAB', schema='sap')
    op.drop_column('lfb1', 'FDGRV', schema='sap')
    op.drop_column('lfb1', 'KVERM', schema='sap')
    op.drop_column('lfb1', 'ZSABE', schema='sap')
    op.drop_column('lfb1', 'EIKTO', schema='sap')
    op.drop_column('lfb1', 'ZINRT', schema='sap')
    op.drop_column('lfb1', 'ZINDT', schema='sap')
    op.drop_column('lfb1', 'PAY_TYPE', schema='sap')
    op.drop_column('lfb1', 'ZWELS', schema='sap')
    op.drop_column('lfb1', 'VZSKZ', schema='sap')
    op.drop_column('lfb1', 'BEGRU', schema='sap')
    op.drop_column('lfb1', 'LOEVM', schema='sap')
    op.drop_column('lfb1', 'SPERR', schema='sap')
    op.drop_column('lfb1', 'ERNAM', schema='sap')
    op.drop_column('lfb1', 'ERDAT', schema='sap')
    op.drop_column('lfb1', 'PERNR', schema='sap')
    op.add_column('lfa1', sa.Column('LAND1', sa.VARCHAR(length=3), autoincrement=False, nullable=True, comment='Country Key'), schema='sap')
    op.alter_column('lfa1', 'STCD1',
               existing_type=sa.VARCHAR(length=16),
               comment='Tax Number 1 (GST/VAT)',
               existing_comment='Tax Number 1 (GST)',
               existing_nullable=True,
               schema='sap')
    op.alter_column('lfa1', 'NAME1',
               existing_type=sa.VARCHAR(length=35),
               comment='Vendor Name',
               existing_comment='Name 1',
               existing_nullable=True,
               schema='sap')
    op.drop_column('lfa1', 'FISKN', schema='sap')
    op.drop_column('lfa1', 'MBRSH', schema='sap')
    op.drop_column('lfa1', 'UPTIM', schema='sap')
    op.drop_column('lfa1', 'UPDAT', schema='sap')
    op.drop_column('lfa1', 'LOEVM', schema='sap')
    op.drop_column('lfa1', 'SPERZ', schema='sap')
    op.drop_column('lfa1', 'SPERR', schema='sap')
    op.drop_column('lfa1', 'ERNAM', schema='sap')
    op.drop_column('lfa1', 'ERDAT', schema='sap')
    op.drop_column('lfa1', 'VBUND', schema='sap')
    op.drop_column('lfa1', 'KONZS', schema='sap')
    op.drop_column('lfa1', 'BRSCH', schema='sap')
    op.drop_column('lfa1', 'STCEG', schema='sap')
    op.drop_column('lfa1', 'STCD3', schema='sap')
    op.drop_column('lfa1', 'STCD2', schema='sap')
    op.drop_column('lfa1', 'LANGU', schema='sap')
    op.drop_column('lfa1', 'SMTP_ADDR', schema='sap')
    op.drop_column('lfa1', 'TELX1', schema='sap')
    op.drop_column('lfa1', 'TELTX', schema='sap')
    op.drop_column('lfa1', 'TELFX', schema='sap')
    op.drop_column('lfa1', 'TELF2', schema='sap')
    op.drop_column('lfa1', 'TELF1', schema='sap')
    op.drop_column('lfa1', 'REGION', schema='sap')
    op.drop_column('lfa1', 'COUNTRY', schema='sap')
    op.drop_column('lfa1', 'HOUSE_NUM1', schema='sap')
    op.drop_column('lfa1', 'STREET', schema='sap')
    op.drop_column('lfa1', 'POST_CODE1', schema='sap')
    op.drop_column('lfa1', 'CITY1', schema='sap')
    op.drop_column('lfa1', 'NAME4', schema='sap')
    op.drop_column('lfa1', 'NAME3', schema='sap')
    op.drop_column('lfa1', 'NAME2', schema='sap')
    op.alter_column('ekpo', 'NETWR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Order Value',
               existing_comment='Net Order Value in PO Currency',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'NETPR',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Net Price',
               existing_comment='Net Price in Purchasing Document',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'MEINS',
               existing_type=sa.VARCHAR(length=3),
               comment='Unit of Measure',
               existing_comment='Order Unit',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekpo', 'EBELP',
               existing_type=sa.VARCHAR(length=5),
               comment='PO Item Number',
               existing_comment='Item Number of Purchasing Document',
               existing_nullable=False,
               schema='sap')
    op.alter_column('ekpo', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchase Order Number',
               existing_comment='Purchasing Document Number',
               existing_nullable=False,
               schema='sap')
    op.drop_column('ekpo', 'ABSKZ', schema='sap')
    op.drop_column('ekpo', 'BWTTY', schema='sap')
    op.drop_column('ekpo', 'BWTAR', schema='sap')
    op.drop_column('ekpo', 'PRSDR', schema='sap')
    op.drop_column('ekpo', 'SPINF', schema='sap')
    op.drop_column('ekpo', 'INSMK', schema='sap')
    op.drop_column('ekpo', 'BONUS', schema='sap')
    op.drop_column('ekpo', 'MWSKZ', schema='sap')
    op.drop_column('ekpo', 'WEBAZ', schema='sap')
    op.drop_column('ekpo', 'AGDAT', schema='sap')
    op.drop_column('ekpo', 'BRTWR', schema='sap')
    op.drop_column('ekpo', 'PEINH', schema='sap')
    op.drop_column('ekpo', 'BPUMN', schema='sap')
    op.drop_column('ekpo', 'BPUMZ', schema='sap')
    op.drop_column('ekpo', 'MATKL', schema='sap')
    op.drop_column('ekpo', 'BEDNR', schema='sap')
    op.drop_column('ekpo', 'LGORT', schema='sap')
    op.drop_column('ekpo', 'WERKS', schema='sap')
    op.drop_column('ekpo', 'BUKRS', schema='sap')
    op.drop_column('ekpo', 'EMATN', schema='sap')
    op.drop_column('ekpo', 'TXZ01', schema='sap')
    op.drop_column('ekpo', 'AEDAT', schema='sap')
    op.drop_column('ekpo', 'STATU', schema='sap')
    op.drop_column('ekpo', 'LOEKZ', schema='sap')
    op.alter_column('ekko', 'BEDAT',
               existing_type=sa.DATE(),
               comment='Purchase Order Date',
               existing_comment='Purchasing Document Date',
               existing_nullable=True,
               schema='sap')
    op.alter_column('ekko', 'EBELN',
               existing_type=sa.VARCHAR(length=10),
               comment='Purchase Order Number',
               existing_comment='Purchasing Document Number',
               existing_nullable=False,
               schema='sap')
    op.drop_column('ekko', 'PROCSTAT', schema='sap')
    op.drop_column('ekko', 'LIBRE', schema='sap')
    op.drop_column('ekko', 'LPNOH', schema='sap')
    op.drop_column('ekko', 'RESWK', schema='sap')
    op.drop_column('ekko', 'KNUMV', schema='sap')
    op.drop_column('ekko', 'BWVKO', schema='sap')
    op.drop_column('ekko', 'KDATE', schema='sap')
    op.drop_column('ekko', 'KDATB', schema='sap')
    op.drop_column('ekko', 'KUFIX', schema='sap')
    op.drop_column('ekko', 'WKURS', schema='sap')
    op.drop_column('ekko', 'EKGRP', schema='sap')
    op.drop_column('ekko', 'EKORG', schema='sap')
    op.drop_column('ekko', 'ZBD2P', schema='sap')
    op.drop_column('ekko', 'ZBD1P', schema='sap')
    op.drop_column('ekko', 'ZBD3T', schema='sap')
    op.drop_column('ekko', 'ZBD2T', schema='sap')
    op.drop_column('ekko', 'ZBD1T', schema='sap')
    op.drop_column('ekko', 'ZTERM', schema='sap')
    op.drop_column('ekko', 'ERNAM', schema='sap')
    op.drop_column('ekko', 'AEDAT', schema='sap')
    op.drop_column('ekko', 'STATU', schema='sap')
    op.drop_column('ekko', 'LOEKZ', schema='sap')
    op.drop_column('ekko', 'BSAKU', schema='sap')
    op.drop_column('ekko', 'BSART', schema='sap')
    op.drop_column('ekko', 'BSTYP', schema='sap')
    op.drop_column('bseg', 'AUFNR', schema='sap')
    op.drop_column('bseg', 'PROJK', schema='sap')
    op.drop_column('bseg', 'LIFNR', schema='sap')
    op.drop_column('bseg', 'KUNNR', schema='sap')
    op.drop_column('bseg', 'FWZUZ', schema='sap')
    op.drop_column('bseg', 'HWZUZ', schema='sap')
    op.drop_column('bseg', 'FWBAS', schema='sap')
    op.drop_column('bseg', 'HWBAS', schema='sap')
    op.drop_column('bseg', 'WMWST', schema='sap')
    op.drop_column('bseg', 'MWSTS', schema='sap')
    op.drop_column('bseg', 'MWSKZ', schema='sap')
    op.drop_column('bseg', 'PARGB', schema='sap')
    op.drop_column('bseg', 'GSBER', schema='sap')
    op.drop_column('bseg', 'UMSKZ', schema='sap')
    op.drop_column('bseg', 'BSCHL', schema='sap')
    op.drop_column('bseg', 'BZIRK', schema='sap')
    op.alter_column('bkpf', 'CPUDT',
               existing_type=sa.DATE(),
               comment='Entry Date',
               existing_comment='Day On Which Accounting Document Was Entered',
               existing_nullable=True,
               schema='sap')
    op.alter_column('bkpf', 'BUDAT',
               existing_type=sa.DATE(),
               comment='Posting Date',
               existing_comment='Posting Date in the Document',
               existing_nullable=True,
               schema='sap')
    op.drop_column('bkpf', 'KZWRS', schema='sap')
    op.drop_column('bkpf', 'KURSF', schema='sap')
    op.drop_column('bkpf', 'WAERS', schema='sap')
    op.drop_column('bkpf', 'BKTXT', schema='sap')
    op.drop_column('bkpf', 'STJAH', schema='sap')
    op.drop_column('bkpf', 'STBLG', schema='sap')
    op.drop_column('bkpf', 'DBBLG', schema='sap')
    op.drop_column('bkpf', 'XBLNR', schema='sap')
    op.drop_column('bkpf', 'BVORG', schema='sap')
    op.drop_column('bkpf', 'TCODE', schema='sap')
    op.drop_column('bkpf', 'WWERT', schema='sap')
    op.drop_column('bkpf', 'UPDDT', schema='sap')
    op.drop_column('bkpf', 'AEDAT', schema='sap')
    op.drop_column('bkpf', 'CPUTM', schema='sap')
    op.drop_column('bkpf', 'MONAT', schema='sap')
    op.drop_column('bkpf', 'BLDAT', schema='sap')
    # ### end Alembic commands ###
