"""add_sap_tables

Revision ID: 9a3d5175725f
Revises: 5d954be544ac
Create Date: 2026-02-18 16:24:15.933592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3d5175725f'
down_revision: Union[str, None] = '5d954be544ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bkpf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BUKRS', sa.String(length=4), nullable=False, comment='Company Code'),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Accounting Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BLART', sa.String(length=2), nullable=True, comment='Document Type'),
    sa.Column('BUDAT', sa.Date(), nullable=True, comment='Posting Date'),
    sa.Column('CPUDT', sa.Date(), nullable=True, comment='Entry Date'),
    sa.Column('USNAM', sa.String(length=12), nullable=True, comment='User Name'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('bseg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BUKRS', sa.String(length=4), nullable=False, comment='Company Code'),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Accounting Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BUZEI', sa.String(length=3), nullable=False, comment='Line Item Number'),
    sa.Column('KOART', sa.String(length=1), nullable=True, comment='Account Type'),
    sa.Column('SHKZG', sa.String(length=1), nullable=True, comment='Debit/Credit Indicator'),
    sa.Column('WRBTR', sa.Float(), nullable=True, comment='Amount in Document Currency'),
    sa.Column('DMBTR', sa.Float(), nullable=True, comment='Amount in Local Currency'),
    sa.Column('HKONT', sa.String(length=10), nullable=True, comment='General Ledger Account'),
    sa.Column('KOSTL', sa.String(length=10), nullable=True, comment='Cost Center'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('ekko',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EBELN', sa.String(length=10), nullable=False, comment='Purchase Order Number'),
    sa.Column('BUKRS', sa.String(length=4), nullable=True, comment='Company Code'),
    sa.Column('LIFNR', sa.String(length=10), nullable=True, comment='Vendor Number'),
    sa.Column('BEDAT', sa.Date(), nullable=True, comment='Purchase Order Date'),
    sa.Column('WAERS', sa.String(length=5), nullable=True, comment='Currency Key'),
    sa.Column('NETWR', sa.Float(), nullable=True, comment='Net Order Value'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('EBELN'),
    schema='sap_layer'
    )
    op.create_table('ekpo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EBELN', sa.String(length=10), nullable=False, comment='Purchase Order Number'),
    sa.Column('EBELP', sa.String(length=5), nullable=False, comment='PO Item Number'),
    sa.Column('MATNR', sa.String(length=18), nullable=True, comment='Material Number'),
    sa.Column('MENGE', sa.Float(), nullable=True, comment='Purchase Order Quantity'),
    sa.Column('MEINS', sa.String(length=3), nullable=True, comment='Unit of Measure'),
    sa.Column('NETPR', sa.Float(), nullable=True, comment='Net Price'),
    sa.Column('NETWR', sa.Float(), nullable=True, comment='Net Order Value'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('lfa1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LIFNR', sa.String(length=10), nullable=False, comment='Vendor Number'),
    sa.Column('NAME1', sa.String(length=35), nullable=True, comment='Vendor Name'),
    sa.Column('LAND1', sa.String(length=3), nullable=True, comment='Country Key'),
    sa.Column('STCD1', sa.String(length=16), nullable=True, comment='Tax Number 1 (GST/VAT)'),
    sa.Column('KTOKK', sa.String(length=4), nullable=True, comment='Vendor Account Group'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('LIFNR'),
    schema='sap_layer'
    )
    op.create_table('lfb1',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LIFNR', sa.String(length=10), nullable=False, comment='Vendor Number'),
    sa.Column('BUKRS', sa.String(length=4), nullable=False, comment='Company Code'),
    sa.Column('AKONT', sa.String(length=10), nullable=True, comment='Reconciliation Account'),
    sa.Column('ZTERM', sa.String(length=4), nullable=True, comment='Payment Terms Key'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('mkpf',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MBLNR', sa.String(length=10), nullable=False, comment='Material Document Number'),
    sa.Column('MJAHR', sa.String(length=4), nullable=False, comment='Material Document Year'),
    sa.Column('BLDAT', sa.Date(), nullable=True, comment='Document Date'),
    sa.Column('BUDAT', sa.Date(), nullable=True, comment='Posting Date'),
    sa.Column('USNAM', sa.String(length=12), nullable=True, comment='User Name'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('mseg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MBLNR', sa.String(length=10), nullable=False, comment='Material Document Number'),
    sa.Column('MJAHR', sa.String(length=4), nullable=False, comment='Material Document Year'),
    sa.Column('ZEILE', sa.String(length=4), nullable=False, comment='Line Item in Material Document'),
    sa.Column('MATNR', sa.String(length=18), nullable=True, comment='Material Number'),
    sa.Column('WERKS', sa.String(length=4), nullable=True, comment='Plant'),
    sa.Column('MENGE', sa.Float(), nullable=True, comment='Quantity'),
    sa.Column('MEINS', sa.String(length=3), nullable=True, comment='Unit of Measure'),
    sa.Column('EBELN', sa.String(length=10), nullable=True, comment='Purchase Order Number'),
    sa.Column('EBELP', sa.String(length=5), nullable=True, comment='PO Item Number'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('rbkp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BLDAT', sa.Date(), nullable=True, comment='Document Date'),
    sa.Column('BUDAT', sa.Date(), nullable=True, comment='Posting Date'),
    sa.Column('LIFNR', sa.String(length=10), nullable=True, comment='Vendor Number'),
    sa.Column('XBLNR', sa.String(length=16), nullable=True, comment='Reference Document Number'),
    sa.Column('WAERS', sa.String(length=5), nullable=True, comment='Currency Key'),
    sa.Column('RMWWR', sa.Float(), nullable=True, comment='Gross Invoice Amount'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    op.create_table('rseg',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('BELNR', sa.String(length=10), nullable=False, comment='Invoice Document Number'),
    sa.Column('GJAHR', sa.String(length=4), nullable=False, comment='Fiscal Year'),
    sa.Column('BUZEI', sa.String(length=3), nullable=False, comment='Line Item Number'),
    sa.Column('EBELN', sa.String(length=10), nullable=True, comment='Purchase Order Number'),
    sa.Column('EBELP', sa.String(length=5), nullable=True, comment='PO Item Number'),
    sa.Column('MATNR', sa.String(length=18), nullable=True, comment='Material Number'),
    sa.Column('MENGE', sa.Float(), nullable=True, comment='Quantity'),
    sa.Column('WRBTR', sa.Float(), nullable=True, comment='Amount in Document Currency'),
    sa.Column('BWTAR', sa.String(length=10), nullable=True, comment='Valuation Type'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sap_layer'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rseg', schema='sap_layer')
    op.drop_table('rbkp', schema='sap_layer')
    op.drop_table('mseg', schema='sap_layer')
    op.drop_table('mkpf', schema='sap_layer')
    op.drop_table('lfb1', schema='sap_layer')
    op.drop_table('lfa1', schema='sap_layer')
    op.drop_table('ekpo', schema='sap_layer')
    op.drop_table('ekko', schema='sap_layer')
    op.drop_table('bseg', schema='sap_layer')
    op.drop_table('bkpf', schema='sap_layer')
    # ### end Alembic commands ###
